'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Clock3, PauseCircle, Play, Plus, Search, Workflow, X } from 'lucide-react';
import { useCrm } from '@/components/CrmProvider';
import { TASK_TYPE_LABELS, formatDate } from '@/lib/constants';

const TYPES=['call','email','whatsapp','linkedin','meeting','follow_up','proposal','research','other'];
export default function CadencesPage(){
  const {supabase,membership,user,team,teamMap,isManager}=useCrm(); const org=membership?.organization_id;
  const [cadences,setCadences]=useState([]); const [steps,setSteps]=useState({}); const [enrollments,setEnrollments]=useState([]); const [q,setQ]=useState(''); const [found,setFound]=useState([]); const [selectedPub,setSelectedPub]=useState(null); const [cadenceId,setCadenceId]=useState(''); const [targetUser,setTargetUser]=useState(user?.id||''); const [showNew,setShowNew]=useState(false); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(true);
  async function load(){if(!org)return;setLoading(true);const [{data:c,error:ce},{data:e,error:ee}]=await Promise.all([supabase.from('cadences').select('*').eq('organization_id',org).eq('active',true).order('name'),supabase.from('cadence_enrollments').select('id,cadence_id,publisher_id,user_id,status,started_at,publishers(name),cadences(name)').eq('organization_id',org).eq('status','active').order('started_at',{ascending:false}).limit(100)]);if(ce||ee)setNotice(ce?.message||ee?.message);setCadences(c||[]);setCadenceId(x=>x||(c?.[0]?.id||''));const ids=(c||[]).map(x=>x.id);if(ids.length){const {data:st}=await supabase.from('cadence_steps').select('*').in('cadence_id',ids).order('position');const map={};(st||[]).forEach(s=>(map[s.cadence_id]||(map[s.cadence_id]=[])).push(s));setSteps(map)}setEnrollments(e||[]);setLoading(false)}
  useEffect(()=>{load()},[org]);
  useEffect(()=>{if(!q.trim()||!org){setFound([]);return}const t=setTimeout(async()=>{const {data}=await supabase.from('publishers').select('id,name,city,state,owner_user_id').eq('organization_id',org).eq('archived',false).ilike('name',`%${q.trim()}%`).order('score',{ascending:false}).limit(12);setFound(data||[])},250);return()=>clearTimeout(t)},[q,org]);
  async function start(){if(!selectedPub||!cadenceId)return;const args={p_organization_id:org,p_cadence_id:cadenceId,p_publisher_id:selectedPub.id,p_user_id:isManager?(targetUser||user.id):user.id};const {error}=await supabase.rpc('crm_start_cadence',args);if(error)setNotice(error.message);else{setNotice(`Cadência iniciada para ${selectedPub.name}. As tarefas já foram colocadas na fila.`);setSelectedPub(null);setQ('');load()}}
  async function stop(e){const {error}=await supabase.rpc('crm_stop_cadence',{p_organization_id:org,p_enrollment_id:e.id});if(error)setNotice(error.message);else{setNotice('Cadência encerrada e tarefas futuras canceladas.');load()}}
  return <div className="page-wrap"><div className="page-head"><div><div className="eyebrow">Ritmo comercial</div><h1>Cadências</h1><p>Organize sequências de tentativas. O CRM cria as tarefas nas datas certas; nenhuma mensagem é enviada automaticamente.</p></div>{isManager&&<button className="btn" onClick={()=>setShowNew(true)}><Plus size={16}/> Nova cadência</button>}</div>{notice&&<div className="notice-bar"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    <div className="cadence-layout"><section className="card panel"><div className="panel-head"><div><h2>Iniciar uma cadência</h2><p>Escolha uma editora e uma sequência de trabalho.</p></div><Play size={20}/></div><div className="cadence-start-form"><label>Buscar editora<div className="search-box"><Search size={17}/><input className="input" value={q} onChange={e=>{setQ(e.target.value);setSelectedPub(null)}} placeholder="Digite o nome da editora"/></div></label>{found.length>0&&!selectedPub&&<div className="cadence-search-results">{found.map(p=><button key={p.id} onClick={()=>{setSelectedPub(p);setQ(p.name);setFound([])}}><strong>{p.name}</strong><span>{[p.city,p.state].filter(Boolean).join(' / ')||'—'}{p.owner_user_id?` · Responsável: ${teamMap[p.owner_user_id]?.full_name||teamMap[p.owner_user_id]?.email||'equipe'}`:' · Sem responsável'}</span></button>)}</div>}<label>Cadência<select value={cadenceId} onChange={e=>setCadenceId(e.target.value)}>{cadences.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>{isManager&&<label>Responsável<select value={targetUser} onChange={e=>setTargetUser(e.target.value)}>{team.filter(m=>m.active).map(m=><option value={m.user_id} key={m.user_id}>{m.full_name||m.email}</option>)}</select></label>}<button className="btn full" disabled={!selectedPub||!cadenceId} onClick={start}><Play size={15}/> Criar tarefas da cadência</button></div></section>
      <section className="card panel"><div className="panel-head"><div><h2>Modelos disponíveis</h2><p>Etapas e intervalos usados para criar tarefas.</p></div><Workflow size={20}/></div><div className="cadence-template-list">{cadences.map(c=><div className="cadence-template" key={c.id}><div><strong>{c.name}</strong><p>{c.description||'Sem descrição.'}</p></div><div className="cadence-steps">{(steps[c.id]||[]).map(s=><div key={s.id}><span>Dia {s.delay_days}</span><strong>{s.title}</strong><small>{TASK_TYPE_LABELS[s.task_type]||s.task_type}</small></div>)}</div></div>)}</div></section>
    </div>
    <section className="card panel" style={{marginTop:16}}><div className="panel-head"><div><h2>Cadências ativas</h2><p>Sequências em andamento e suas tarefas futuras.</p></div><Clock3 size={20}/></div>{loading?<div className="table-empty">Carregando cadências…</div>:enrollments.length?<div className="active-cadence-list">{enrollments.map(e=><div className="active-cadence-row" key={e.id}><div><Link href={`/app/editoras/${e.publisher_id}`}><strong>{e.publishers?.name||'Editora'}</strong></Link><span>{e.cadences?.name||'Cadência'} · {teamMap[e.user_id]?.full_name||teamMap[e.user_id]?.email||'Equipe'}</span><small>Iniciada em {formatDate(e.started_at,true)}</small></div>{(e.user_id===user.id||isManager)&&<button className="btn secondary small" onClick={()=>stop(e)}><PauseCircle size={14}/> Encerrar</button>}</div>)}</div>:<div className="empty-state"><Workflow/><strong>Nenhuma cadência ativa.</strong><p>Comece por uma editora da sua carteira ou uma conta sem responsável.</p></div>}</section>
    {showNew&&<CadenceModal supabase={supabase} org={org} user={user} onClose={()=>setShowNew(false)} onSaved={()=>{setShowNew(false);setNotice('Cadência criada.');load()}}/>}
  </div>
}
function CadenceModal({supabase,org,user,onClose,onSaved}){const [name,setName]=useState('');const [description,setDescription]=useState('');const [rows,setRows]=useState([{delay_days:0,task_type:'call',title:'1ª tentativa · Ligação'},{delay_days:2,task_type:'email',title:'2ª tentativa · E-mail'}]);const [err,setErr]=useState('');function setRow(i,k,v){setRows(x=>x.map((r,n)=>n===i?{...r,[k]:v}:r))}async function save(e){e.preventDefault();setErr('');const {data:c,error}=await supabase.from('cadences').insert({organization_id:org,name,description:description||null,created_by:user.id}).select('id').single();if(error){setErr(error.message);return}const payload=rows.map((r,i)=>({cadence_id:c.id,position:i+1,delay_days:Number(r.delay_days)||0,task_type:r.task_type,title:r.title}));const {error:se}=await supabase.from('cadence_steps').insert(payload);if(se)setErr(se.message);else onSaved()}return <div className="modal-backdrop"><form className="modal cadence-modal" onSubmit={save}><div className="modal-head"><div><h3>Nova cadência</h3><p>Defina tarefas e quantos dias após o início cada uma deve acontecer.</p></div><button type="button" onClick={onClose}><X/></button></div>{err&&<div className="notice error">{err}</div>}<div className="form-grid"><label className="span-2">Nome<input className="input" required value={name} onChange={e=>setName(e.target.value)}/></label><label className="span-2">Descrição<input className="input" value={description} onChange={e=>setDescription(e.target.value)}/></label></div><div className="cadence-builder">{rows.map((r,i)=><div className="cadence-builder-row" key={i}><label>Dia<input className="input" type="number" min="0" value={r.delay_days} onChange={e=>setRow(i,'delay_days',e.target.value)}/></label><label>Tipo<select value={r.task_type} onChange={e=>setRow(i,'task_type',e.target.value)}>{TYPES.map(t=><option key={t} value={t}>{TASK_TYPE_LABELS[t]||t}</option>)}</select></label><label>Tarefa<input className="input" required value={r.title} onChange={e=>setRow(i,'title',e.target.value)}/></label>{rows.length>1&&<button type="button" className="icon-btn" onClick={()=>setRows(x=>x.filter((_,n)=>n!==i))}><X size={15}/></button>}</div>)}</div><button type="button" className="btn secondary small" onClick={()=>setRows(x=>[...x,{delay_days:(Number(x.at(-1)?.delay_days)||0)+3,task_type:'follow_up',title:'Novo follow-up'}])}><Plus size={14}/> Adicionar etapa</button><div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancelar</button><button className="btn">Salvar cadência</button></div></form></div>}
