'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Download, FileText, Paperclip, Search, Trash2, Upload, X } from 'lucide-react';
import { useCrm } from '@/components/CrmProvider';
import { formatDate } from '@/lib/constants';

const MAX_SIZE=15*1024*1024;
const ACCEPT='.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.jpg,.jpeg,.png,.webp';
function safeName(name='arquivo'){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').slice(-120)||'arquivo'}
function bytes(n){const x=Number(n||0);if(x<1024)return `${x} B`;if(x<1024**2)return `${(x/1024).toFixed(1)} KB`;return `${(x/1024**2).toFixed(1)} MB`}

export default function AttachmentsPage(){
  const {supabase,membership,user,isManager,teamMap}=useCrm(); const org=membership?.organization_id;
  const [rows,setRows]=useState([]); const [q,setQ]=useState(''); const [found,setFound]=useState([]); const [publisher,setPublisher]=useState(null); const [file,setFile]=useState(null); const [description,setDescription]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
  async function load(){if(!org)return;let query=supabase.from('attachments').select('id,organization_id,publisher_id,uploaded_by,file_name,storage_path,mime_type,size_bytes,description,created_at,publishers(name)').eq('organization_id',org).order('created_at',{ascending:false}).limit(120);if(publisher?.id)query=query.eq('publisher_id',publisher.id);const {data,error}=await query;if(error)setNotice(error.message);setRows(data||[])}
  useEffect(()=>{load()},[org,publisher?.id,isManager,user?.id]);
  useEffect(()=>{if(!q.trim()||!org||publisher){setFound([]);return}const t=setTimeout(async()=>{let query=supabase.from('publishers').select('id,name,city,state').eq('organization_id',org).eq('archived',false).ilike('name',`%${q.trim()}%`);if(!isManager)query=query.eq('owner_user_id',user?.id);const {data}=await query.order('score',{ascending:false}).limit(12);setFound(data||[])},250);return()=>clearTimeout(t)},[q,org,publisher,isManager,user?.id]);
  async function upload(e){e.preventDefault();if(!publisher||!file)return;if(file.size>MAX_SIZE){setNotice('O arquivo ultrapassa o limite de 15 MB.');return}setBusy(true);setNotice('');const path=`${org}/${publisher.id}/${user.id}/${crypto.randomUUID()}-${safeName(file.name)}`;const {error:up}=await supabase.storage.from('crm-attachments').upload(path,file,{contentType:file.type||undefined,upsert:false});if(up){setNotice(up.message);setBusy(false);return}const {error:meta}=await supabase.from('attachments').insert({organization_id:org,publisher_id:publisher.id,uploaded_by:user.id,file_name:file.name,storage_path:path,mime_type:file.type||null,size_bytes:file.size,description:description||null});if(meta){await supabase.storage.from('crm-attachments').remove([path]);setNotice(meta.message);setBusy(false);return}setFile(null);setDescription('');const input=document.getElementById('crm-attachment-file');if(input)input.value='';setNotice('Anexo salvo.');await load();setBusy(false)}
  async function download(row){const {data,error}=await supabase.storage.from('crm-attachments').createSignedUrl(row.storage_path,120);if(error)setNotice(error.message);else window.open(data.signedUrl,'_blank','noopener,noreferrer')}
  async function remove(row){if(!confirm(`Excluir o anexo “${row.file_name}”?`))return;const {error:se}=await supabase.storage.from('crm-attachments').remove([row.storage_path]);if(se){setNotice(se.message);return}const {error}=await supabase.from('attachments').delete().eq('id',row.id);if(error)setNotice(error.message);else{setNotice('Anexo excluído.');load()}}
  return <div className="page-wrap"><div className="page-head"><div><div className="eyebrow">Arquivos comerciais</div><h1>Anexos</h1><p>{isManager?'Adicione e consulte documentos vinculados às editoras da equipe.':'Adicione e consulte documentos vinculados às editoras da sua carteira.'}</p></div><Paperclip size={28}/></div>{notice&&<div className="notice-bar"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    <div className="attachments-layout"><section className="card panel"><div className="panel-head"><div><h2>Novo anexo</h2><p>Selecione uma editora da sua carteira antes de enviar o arquivo.</p></div><Upload size={20}/></div><form className="attachment-form" onSubmit={upload}><label>Editora<div className="search-box"><Search size={17}/><input className="input" value={q} onChange={e=>{setQ(e.target.value);setPublisher(null)}} placeholder="Buscar editora"/></div></label>{found.length>0&&!publisher&&<div className="attachment-search-results">{found.map(p=><button type="button" key={p.id} onClick={()=>{setPublisher(p);setQ(p.name);setFound([])}}><strong>{p.name}</strong><span>{[p.city,p.state].filter(Boolean).join(' / ')||'—'}</span></button>)}</div>}{publisher&&<div className="selected-publisher"><div><strong>{publisher.name}</strong><span>{[publisher.city,publisher.state].filter(Boolean).join(' / ')||'Editora selecionada'}</span></div><button type="button" className="link-btn" onClick={()=>{setPublisher(null);setQ('')}}>Trocar</button></div>}<label>Arquivo<input id="crm-attachment-file" className="input file-input" type="file" accept={ACCEPT} onChange={e=>setFile(e.target.files?.[0]||null)}/><small>PDF, Office, CSV, TXT ou imagem · até 15 MB.</small></label><label>Descrição opcional<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: proposta enviada em agosto"/></label>{file&&<div className="file-preview"><FileText size={18}/><div><strong>{file.name}</strong><span>{bytes(file.size)}</span></div></div>}<button className="btn full" disabled={!publisher||!file||busy}>{busy?'Enviando…':<><Upload size={15}/> Salvar anexo</>}</button></form></section>
      <section className="card panel"><div className="panel-head"><div><h2>{publisher?`Arquivos · ${publisher.name}`:'Arquivos recentes'}</h2><p>{publisher?'Documentos vinculados a esta editora.':isManager?'Últimos documentos adicionados pela equipe.':'Últimos documentos disponíveis na sua carteira.'}</p></div>{publisher&&<button className="btn secondary small" onClick={()=>{setPublisher(null);setQ('')}}>Ver todos</button>}</div>{rows.length?<div className="attachment-list">{rows.map(r=><article className="attachment-row" key={r.id}><div className="attachment-file-icon"><FileText/></div><div className="attachment-main"><Link href={`/app/editoras/${r.publisher_id}`}><strong>{r.file_name}</strong></Link><span>{r.publishers?.name||'Editora'} · {bytes(r.size_bytes)}</span>{r.description&&<p>{r.description}</p>}<small>{formatDate(r.created_at,true)} · {teamMap[r.uploaded_by]?.full_name||teamMap[r.uploaded_by]?.email||'Equipe'}</small></div><div className="attachment-actions"><button className="icon-btn" title="Baixar" onClick={()=>download(r)}><Download size={16}/></button>{(r.uploaded_by===user.id||isManager)&&<button className="icon-btn danger-icon" title="Excluir" onClick={()=>remove(r)}><Trash2 size={16}/></button>}</div></article>)}</div>:<div className="empty-state"><Paperclip/><strong>Nenhum anexo nesta visão.</strong><p>Os documentos adicionados aparecerão aqui.</p></div>}</section></div>
  </div>
}
