'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Bell, BellRing, CheckCheck, CheckCircle2, Clock3, Plus, Search, X } from 'lucide-react';
import { useCrm } from '@/components/CrmProvider';
import { PRIORITY_LABELS, TASK_TYPE_LABELS, formatDate } from '@/lib/constants';

const AUTOMATION_LABELS={meeting_preparation:'Preparação automática',meeting_outcome:'Resultado automático',meeting_follow_up:'Follow-up automático'};

export default function TasksPage(){
  const {supabase,membership,user,activityVersion,isManager,teamMap}=useCrm();const org=membership?.organization_id;
  const [rows,setRows]=useState([]);const [publishers,setPublishers]=useState([]);const [reminders,setReminders]=useState([]);const [status,setStatus]=useState('open');const [scope,setScope]=useState('mine');const [q,setQ]=useState('');const [show,setShow]=useState(false);const [notice,setNotice]=useState('');const [loading,setLoading]=useState(true);

  async function loadReminders(){
    if(!org||!user?.id)return;
    const {error:refreshError}=await supabase.rpc('crm_refresh_notifications',{p_organization_id:org});
    if(refreshError)setNotice(refreshError.message);
    const {data,error}=await supabase.from('notifications').select('id,title,body,severity,href,read_at,created_at').eq('organization_id',org).eq('user_id',user.id).is('resolved_at',null).is('read_at',null).order('created_at',{ascending:false}).limit(30);
    if(error)setNotice(error.message);setReminders(data||[]);window.dispatchEvent(new Event('crm-notifications-changed'));
  }
  async function load(){
    if(!org||!user)return;setLoading(true);
    let query=supabase.from('tasks').select('id,title,description,task_type,due_at,status,priority,publisher_id,assigned_to,created_at,meeting_id,automation_key,publishers(name)').eq('organization_id',org);
    if(!isManager||scope==='mine')query=query.eq('assigned_to',user.id);
    if(status==='open')query=query.in('status',['open','in_progress']);else if(status!=='all')query=query.eq('status',status);
    const [{data,error},{data:pubs}]=await Promise.all([query.order('due_at',{ascending:true,nullsFirst:false}).limit(250),supabase.from('publishers').select('id,name').eq('organization_id',org).eq('archived',false).order('name').limit(500)]);
    if(error)setNotice(error.message);setRows(data||[]);setPublishers(pubs||[]);await loadReminders();setLoading(false);
  }
  useEffect(()=>{load()},[org,user?.id,status,scope,isManager,activityVersion]);

  const filtered=useMemo(()=>{const needle=q.trim().toLowerCase();return needle?rows.filter(t=>`${t.title} ${t.publishers?.name||''} ${teamMap[t.assigned_to]?.full_name||teamMap[t.assigned_to]?.email||''}`.toLowerCase().includes(needle)):rows},[rows,q,teamMap]);
  async function done(id){const {error}=await supabase.from('tasks').update({status:'done',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('organization_id',org).eq('id',id);if(error)setNotice(error.message);else load()}
  async function markReminder(id){const now=new Date().toISOString();const {error}=await supabase.from('notifications').update({read_at:now,updated_at:now}).eq('organization_id',org).eq('user_id',user.id).eq('id',id);if(error)setNotice(error.message);else{setReminders(current=>current.filter(item=>item.id!==id));window.dispatchEvent(new Event('crm-notifications-changed'))}}
  async function markAllReminders(){const now=new Date().toISOString();const {error}=await supabase.from('notifications').update({read_at:now,updated_at:now}).eq('organization_id',org).eq('user_id',user.id).is('resolved_at',null).is('read_at',null);if(error)setNotice(error.message);else{setReminders([]);setNotice('Lembretes revisados.');window.dispatchEvent(new Event('crm-notifications-changed'))}}
  const teamView=isManager&&scope==='team';

  return <div className="page-wrap"><div className="page-head"><div><div className="eyebrow">Execução</div><h1>{teamView?'Fila da equipe':'Minha fila'}</h1><p>{teamView?'Acompanhe tarefas, lembretes automáticos de reuniões e prazos da equipe.':'Um único lugar para tarefas, follow-ups, reuniões e alertas que exigem sua atenção.'}</p></div><button className="btn" onClick={()=>setShow(true)}><Plus size={16}/> Nova tarefa</button></div>{notice&&<div className="notice-bar"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}

    {!teamView&&reminders.length>0&&<section className="card attention-inbox"><div className="attention-head"><div><span className="attention-icon"><BellRing size={17}/></span><div><strong>Atenção agora</strong><p>{reminders.length} lembrete{reminders.length===1?'':'s'} ainda não revisado{reminders.length===1?'':'s'}.</p></div></div><button className="btn secondary small" type="button" onClick={markAllReminders}><CheckCheck size={14}/> Marcar todos como lidos</button></div><div className="attention-list">{reminders.slice(0,4).map(item=><article key={item.id} className={`attention-row ${item.severity||'info'}`}><span className="attention-bell">{item.severity==='urgent'?<BellRing size={15}/>:<Bell size={15}/>}</span><div><strong>{item.title}</strong><p>{item.body||'Há uma ação esperando por você.'}</p><small>{formatDate(item.created_at,true)}</small></div><div className="attention-actions">{item.href&&<Link href={item.href} className="btn secondary small" onClick={()=>markReminder(item.id)}>Abrir</Link>}<button type="button" className="link-btn" onClick={()=>markReminder(item.id)}>Lido</button></div></article>)}</div>{reminders.length>4&&<div className="attention-more">+{reminders.length-4} lembrete{reminders.length-4===1?'':'s'} — marque os itens revisados para avançar a fila.</div>}</section>}

    <div className="toolbar"><div className="search-box"><Search size={17}/><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar tarefa, editora ou pessoa"/></div>{isManager&&<div className="chips"><button className={`chip ${scope==='mine'?'active':''}`} onClick={()=>setScope('mine')}>Minhas</button><button className={`chip ${scope==='team'?'active':''}`} onClick={()=>setScope('team')}>Equipe</button></div>}<div className="chips"><button className={`chip ${status==='open'?'active':''}`} onClick={()=>setStatus('open')}>Em aberto</button><button className={`chip ${status==='done'?'active':''}`} onClick={()=>setStatus('done')}>Concluídas</button><button className={`chip ${status==='all'?'active':''}`} onClick={()=>setStatus('all')}>Todas</button></div></div>
    <section className="card panel">{loading?<div className="table-empty">Carregando fila…</div>:filtered.length?<div className="task-list">{filtered.map(t=>{const late=t.status!=='done'&&t.due_at&&new Date(t.due_at)<new Date();const mine=t.assigned_to===user.id;const assignee=teamMap[t.assigned_to]?.full_name||teamMap[t.assigned_to]?.email||'Equipe';return <div className="task-row" key={t.id}>{t.status!=='done'&&mine?<button className="task-check" onClick={()=>done(t.id)} title="Concluir"><CheckCircle2 size={19}/></button>:<CheckCircle2 size={19} style={{color:t.status==='done'?'#15803d':'#98a2b3'}}/>}<div className="task-main"><div className="task-title-line"><strong>{t.title}</strong>{t.automation_key&&<span className="badge blue auto-badge">{AUTOMATION_LABELS[t.automation_key]||'Automático'}</span>}</div><span>{t.publisher_id?<Link href={`/app/editoras/${t.publisher_id}`}>{t.publishers?.name||'Abrir editora'}</Link>:'Sem editora'} · {TASK_TYPE_LABELS[t.task_type]||t.task_type} · {PRIORITY_LABELS[t.priority]||t.priority}{teamView?` · ${assignee}`:''}</span>{t.description&&<span>{t.description}</span>}</div><div className={`task-due ${late?'late':''}`}><Clock3 size={14}/>{t.due_at?formatDate(t.due_at,true):'Sem prazo'}</div></div>})}</div>:<div className="empty-state"><CheckCircle2/><strong>Nenhuma tarefa nesta visão.</strong><p>{teamView?'A equipe não tem tarefas que correspondam aos filtros atuais.':'Sua fila está limpa. Novos próximos passos e lembretes de reunião aparecerão aqui.'}</p></div>}</section>
    {show&&<NewTask supabase={supabase} org={org} user={user} publishers={publishers} onClose={()=>setShow(false)} onSaved={()=>{setShow(false);setNotice('Tarefa criada.');load()}}/>}
    <style jsx>{`.attention-inbox{padding:0;margin-bottom:14px;overflow:hidden;border-color:#f0d7a6}.attention-head{padding:12px 14px;background:#fffcf5;display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid #f6e6c5}.attention-head>div{display:flex;align-items:center;gap:9px}.attention-head strong{font-size:12px}.attention-head p{margin:1px 0 0;font-size:10px;color:#667085}.attention-icon{width:30px;height:30px;border-radius:8px;background:#fff4d9;color:#b54708;display:grid;place-items:center}.attention-list{display:grid}.attention-row{display:grid;grid-template-columns:26px minmax(0,1fr) auto;gap:9px;padding:10px 14px;border-top:1px solid #f0f1f3;align-items:center}.attention-row:first-child{border-top:0}.attention-bell{color:#667085}.attention-row.urgent .attention-bell{color:#b42318}.attention-row.warning .attention-bell{color:#b54708}.attention-row strong{display:block;font-size:11px}.attention-row p{margin:2px 0;font-size:10px;color:#475467}.attention-row small{font-size:9px;color:#98a2b3}.attention-actions{display:flex;align-items:center;gap:4px}.attention-more{padding:8px 14px;background:#fcfcfd;border-top:1px solid #f0f1f3;font-size:9px;color:#667085}.task-title-line{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.auto-badge{font-size:8px!important}@media(max-width:700px){.attention-head{align-items:flex-start;flex-direction:column}.attention-row{grid-template-columns:24px 1fr}.attention-actions{grid-column:2;justify-content:flex-start}}`}</style>
  </div>
}
function NewTask({supabase,org,user,publishers,onClose,onSaved}){const [f,setF]=useState({title:'',description:'',publisher_id:'',task_type:'follow_up',priority:'medium',due_at:''});const [err,setErr]=useState('');async function save(e){e.preventDefault();const {error}=await supabase.from('tasks').insert({organization_id:org,publisher_id:f.publisher_id||null,assigned_to:user.id,created_by:user.id,title:f.title,description:f.description||null,task_type:f.task_type,priority:f.priority,status:'open',due_at:f.due_at?new Date(f.due_at).toISOString():null});if(error)setErr(error.message);else onSaved()}return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><h3>Nova tarefa</h3><p>Inclua o próximo passo na sua fila.</p></div><button type="button" onClick={onClose}><X/></button></div>{err&&<div className="notice error">{err}</div>}<div className="form-grid"><label className="span-2">Título<input required className="input" value={f.title} onChange={e=>setF(x=>({...x,title:e.target.value}))}/></label><label className="span-2">Editora<select value={f.publisher_id} onChange={e=>setF(x=>({...x,publisher_id:e.target.value}))}><option value="">Sem editora vinculada</option>{publishers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Tipo<select value={f.task_type} onChange={e=>setF(x=>({...x,task_type:e.target.value}))}>{Object.entries(TASK_TYPE_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Prioridade<select value={f.priority} onChange={e=>setF(x=>({...x,priority:e.target.value}))}>{Object.entries(PRIORITY_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="span-2">Prazo<input type="datetime-local" className="input" value={f.due_at} onChange={e=>setF(x=>({...x,due_at:e.target.value}))}/></label><label className="span-2">Descrição<textarea rows={3} value={f.description} onChange={e=>setF(x=>({...x,description:e.target.value}))}/></label></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancelar</button><button className="btn">Salvar tarefa</button></div></form></div>}
