'use client';
import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, Plus, Search, X } from 'lucide-react';
import { useCrm } from '@/components/CrmProvider';
import { PRIORITY_LABELS, TASK_TYPE_LABELS, formatDate } from '@/lib/constants';

export default function TasksPage(){
  const {supabase,membership,user,activityVersion,isManager,teamMap}=useCrm();const org=membership?.organization_id;
  const [rows,setRows]=useState([]);const [publishers,setPublishers]=useState([]);const [status,setStatus]=useState('open');const [scope,setScope]=useState('mine');const [q,setQ]=useState('');const [show,setShow]=useState(false);const [notice,setNotice]=useState('');const [loading,setLoading]=useState(true);
  async function load(){if(!org||!user)return;setLoading(true);let query=supabase.from('tasks').select('id,title,description,task_type,due_at,status,priority,publisher_id,assigned_to,created_at,publishers(name)').eq('organization_id',org);if(!isManager||scope==='mine')query=query.eq('assigned_to',user.id);if(status==='open')query=query.in('status',['open','in_progress']);else if(status!=='all')query=query.eq('status',status);const [{data,error},{data:pubs}]=await Promise.all([query.order('due_at',{ascending:true,nullsFirst:false}).limit(250),supabase.from('publishers').select('id,name').eq('organization_id',org).eq('archived',false).order('name').limit(500)]);if(error)setNotice(error.message);setRows(data||[]);setPublishers(pubs||[]);setLoading(false)}
  useEffect(()=>{load()},[org,user?.id,status,scope,isManager,activityVersion]);
  const filtered=useMemo(()=>{const needle=q.trim().toLowerCase();return needle?rows.filter(t=>`${t.title} ${t.publishers?.name||''} ${teamMap[t.assigned_to]?.full_name||teamMap[t.assigned_to]?.email||''}`.toLowerCase().includes(needle)):rows},[rows,q,teamMap]);
  async function done(id){const {error}=await supabase.from('tasks').update({status:'done',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('organization_id',org).eq('id',id);if(error)setNotice(error.message);else load()}
  const teamView=isManager&&scope==='team';
  return <div className="page-wrap"><div className="page-head"><div><div className="eyebrow">Execução</div><h1>{teamView?'Fila da equipe':'Minha fila'}</h1><p>{teamView?'Acompanhe tarefas e prazos atribuídos às pessoas da equipe.':'Organize e conclua seus follow-ups, ligações e demais tarefas com prazo.'}</p></div><button className="btn" onClick={()=>setShow(true)}><Plus size={16}/> Nova tarefa</button></div>{notice&&<div className="notice-bar"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    <div className="toolbar"><div className="search-box"><Search size={17}/><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar tarefa, editora ou pessoa"/></div>{isManager&&<div className="chips"><button className={`chip ${scope==='mine'?'active':''}`} onClick={()=>setScope('mine')}>Minhas</button><button className={`chip ${scope==='team'?'active':''}`} onClick={()=>setScope('team')}>Equipe</button></div>}<div className="chips"><button className={`chip ${status==='open'?'active':''}`} onClick={()=>setStatus('open')}>Em aberto</button><button className={`chip ${status==='done'?'active':''}`} onClick={()=>setStatus('done')}>Concluídas</button><button className={`chip ${status==='all'?'active':''}`} onClick={()=>setStatus('all')}>Todas</button></div></div>
    <section className="card panel">{loading?<div className="table-empty">Carregando fila…</div>:filtered.length?<div className="task-list">{filtered.map(t=>{const late=t.status!=='done'&&t.due_at&&new Date(t.due_at)<new Date();const mine=t.assigned_to===user.id;const assignee=teamMap[t.assigned_to]?.full_name||teamMap[t.assigned_to]?.email||'Equipe';return <div className="task-row" key={t.id}>{t.status!=='done'&&mine?<button className="task-check" onClick={()=>done(t.id)} title="Concluir"><CheckCircle2 size={19}/></button>:<CheckCircle2 size={19} style={{color:t.status==='done'?'#15803d':'#98a2b3'}}/>}<div className="task-main"><strong>{t.title}</strong><span>{t.publishers?.name||'Sem editora'} · {TASK_TYPE_LABELS[t.task_type]||t.task_type} · {PRIORITY_LABELS[t.priority]||t.priority}{teamView?` · ${assignee}`:''}</span>{t.description&&<span>{t.description}</span>}</div><div className={`task-due ${late?'late':''}`}><Clock3 size={14}/>{t.due_at?formatDate(t.due_at,true):'Sem prazo'}</div></div>})}</div>:<div className="empty-state"><CheckCircle2/><strong>Nenhuma tarefa nesta visão.</strong><p>{teamView?'A equipe não tem tarefas que correspondam aos filtros atuais.':'Crie uma tarefa quando houver um próximo passo.'}</p></div>}</section>
    {show&&<NewTask supabase={supabase} org={org} user={user} publishers={publishers} onClose={()=>setShow(false)} onSaved={()=>{setShow(false);setNotice('Tarefa criada.');load()}}/>}
  </div>
}
function NewTask({supabase,org,user,publishers,onClose,onSaved}){const [f,setF]=useState({title:'',description:'',publisher_id:'',task_type:'follow_up',priority:'medium',due_at:''});const [err,setErr]=useState('');async function save(e){e.preventDefault();const {error}=await supabase.from('tasks').insert({organization_id:org,publisher_id:f.publisher_id||null,assigned_to:user.id,created_by:user.id,title:f.title,description:f.description||null,task_type:f.task_type,priority:f.priority,status:'open',due_at:f.due_at?new Date(f.due_at).toISOString():null});if(error)setErr(error.message);else onSaved()}return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><h3>Nova tarefa</h3><p>Inclua o próximo passo na sua fila.</p></div><button type="button" onClick={onClose}><X/></button></div>{err&&<div className="notice error">{err}</div>}<div className="form-grid"><label className="span-2">Título<input required className="input" value={f.title} onChange={e=>setF(x=>({...x,title:e.target.value}))}/></label><label className="span-2">Editora<select value={f.publisher_id} onChange={e=>setF(x=>({...x,publisher_id:e.target.value}))}><option value="">Sem editora vinculada</option>{publishers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Tipo<select value={f.task_type} onChange={e=>setF(x=>({...x,task_type:e.target.value}))}>{Object.entries(TASK_TYPE_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Prioridade<select value={f.priority} onChange={e=>setF(x=>({...x,priority:e.target.value}))}>{Object.entries(PRIORITY_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="span-2">Prazo<input type="datetime-local" className="input" value={f.due_at} onChange={e=>setF(x=>({...x,due_at:e.target.value}))}/></label><label className="span-2">Descrição<textarea rows={3} value={f.description} onChange={e=>setF(x=>({...x,description:e.target.value}))}/></label></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancelar</button><button className="btn">Salvar tarefa</button></div></form></div>}
