'use client';
import { useState } from 'react';
import { CheckCircle2, Download, FileSpreadsheet, Upload, X } from 'lucide-react';
import { useCrm } from '@/components/CrmProvider';

const TARGETS=[
  ['', 'Ignorar coluna'],['name','Nome da editora *'],['legal_name','Razão social'],['trade_name','Nome fantasia'],['cnpj','CNPJ'],['website','Site'],['country','País'],['city','Cidade'],['state','UF'],['phone','Telefone'],['general_email','E-mail geral'],['profile','Perfil / descrição'],['company_size','Porte'],['book_types','Tipos de livros / segmento'],['priority','Prioridade'],['stage_name','Etapa do pipeline'],['notes','Observações']
];
const ALIASES={
  name:['nome','editora','nome da editora','publisher','empresa'],legal_name:['razao social','razão social','nome empresarial'],trade_name:['nome fantasia','fantasia'],cnpj:['cnpj','documento'],website:['site','website','url'],country:['pais','país','country'],city:['cidade','municipio','município','city'],state:['uf','estado','state'],phone:['telefone','fone','phone','celular'],general_email:['email','e-mail','email geral','e-mail geral'],profile:['perfil','descricao','descrição','profile'],company_size:['porte','tamanho','company size'],book_types:['tipos de livros','tipo de livro','segmento','segmentos','book types'],priority:['prioridade','priority'],stage_name:['etapa','status','pipeline','stage'],notes:['observacoes','observações','notas','notes']
};
function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase().replace(/\s+/g,' ')}
function detectDelimiter(text){const line=(text.split(/\r?\n/).find(Boolean)||'');const counts={',':0,';':0,'\t':0};let quoted=false;for(let i=0;i<line.length;i++){if(line[i]==='"')quoted=!quoted;else if(!quoted&&Object.prototype.hasOwnProperty.call(counts,line[i]))counts[line[i]]++}return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0]}
function parseDelimited(text,delimiter){const out=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===delimiter&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()!==''))out.push(row);row=[]}else cell+=ch}row.push(cell);if(row.some(v=>String(v).trim()!==''))out.push(row);return out}
function autoMap(headers){const used=new Set();return headers.map(h=>{const n=norm(h);for(const [key,aliases] of Object.entries(ALIASES)){if(!used.has(key)&&aliases.some(a=>norm(a)===n)){used.add(key);return key}}return ''})}

export default function ImportPage(){
  const {supabase,membership,isAdmin}=useCrm(); const org=membership?.organization_id;
  const [fileName,setFileName]=useState(''); const [headers,setHeaders]=useState([]); const [rawRows,setRawRows]=useState([]); const [mapping,setMapping]=useState([]); const [mode,setMode]=useState('skip'); const [progress,setProgress]=useState(0); const [busy,setBusy]=useState(false); const [result,setResult]=useState(null); const [notice,setNotice]=useState('');
  const transformed=rawRows.map((row,idx)=>{const obj={_row:String(idx+2)};mapping.forEach((key,i)=>{if(key)obj[key]=String(row[i]??'').trim()});return obj});
  const valid=transformed.filter(r=>r.name?.trim()); const invalidCount=transformed.length-valid.length; const nameMapped=mapping.includes('name');
  if(!isAdmin)return <div className="page-wrap"><div className="card panel"><h2>Acesso restrito</h2><p className="muted">A importação de dados cadastrais é exclusiva de administradores.</p></div></div>;
  async function choose(e){const file=e.target.files?.[0];if(!file)return;setNotice('');setResult(null);const text=await file.text();const delimiter=detectDelimiter(text);const matrix=parseDelimited(text,delimiter);if(matrix.length<2){setNotice('O arquivo precisa ter uma linha de cabeçalho e pelo menos uma linha de dados.');return}const hs=matrix[0].map((h,i)=>String(h).replace(/^\uFEFF/,'').trim()||`Coluna ${i+1}`);setFileName(file.name);setHeaders(hs);setRawRows(matrix.slice(1).filter(r=>r.some(v=>String(v).trim())));setMapping(autoMap(hs));setProgress(0)}
  function setMap(index,value){setMapping(m=>m.map((x,i)=>i===index?value:(value&&x===value?'':x)))}
  async function runImport(){if(!nameMapped||!valid.length)return;setBusy(true);setNotice('');setResult(null);setProgress(0);const totals={inserted:0,updated:0,skipped:invalidCount,errors:0,details:[]};const BATCH=200;for(let i=0;i<valid.length;i+=BATCH){const batch=valid.slice(i,i+BATCH);const {data,error}=await supabase.rpc('crm_import_publishers',{p_organization_id:org,p_rows:batch,p_mode:mode});if(error){setNotice(`A importação parou no lote ${Math.floor(i/BATCH)+1}: ${error.message}`);setBusy(false);return}totals.inserted+=Number(data?.inserted||0);totals.updated+=Number(data?.updated||0);totals.skipped+=Number(data?.skipped||0);totals.errors+=Number(data?.errors||0);totals.details.push(...(data?.details||[]));setProgress(Math.min(100,Math.round((Math.min(i+BATCH,valid.length)/valid.length)*100)))}setResult(totals);setNotice('Importação concluída.');setBusy(false)}
  function downloadTemplate(){const csv='Nome da editora;Razão social;CNPJ;Site;Cidade;UF;Telefone;E-mail geral;Porte;Tipos de livros;Prioridade;Etapa;Observações\nEditora Exemplo Ltda;Editora Exemplo Ltda;00.000.000/0001-00;https://exemplo.com;São Paulo;SP;(11) 0000-0000;contato@exemplo.com;Médio;Literatura;medium;A prospectar;Exemplo de linha\n';const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='modelo-importacao-editoras.csv';a.click();URL.revokeObjectURL(a.href)}
  return <div className="page-wrap"><div className="page-head"><div><div className="eyebrow">Dados em massa</div><h1>Importar editoras</h1><p>Envie um CSV, confira o mapeamento das colunas e veja uma prévia antes de gravar. Nada é importado sem sua confirmação.</p></div><button className="btn secondary" onClick={downloadTemplate}><Download size={16}/> Baixar modelo</button></div>{notice&&<div className="notice-bar"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    <section className="card panel import-upload"><div className="panel-head"><div><h2>1. Escolher arquivo</h2><p>CSV separado por vírgula, ponto e vírgula ou tabulação. Campos entre aspas são suportados.</p></div><FileSpreadsheet size={21}/></div><label className="import-drop"><Upload size={25}/><strong>{fileName||'Selecionar arquivo CSV'}</strong><span>{fileName?`${rawRows.length.toLocaleString('pt-BR')} linhas encontradas`:'Clique para procurar no computador'}</span><input type="file" accept=".csv,text/csv,text/plain" onChange={choose}/></label></section>
    {headers.length>0&&<><section className="card panel" style={{marginTop:16}}><div className="panel-head"><div><h2>2. Mapear colunas</h2><p>Associe cada coluna do arquivo ao campo correto do CRM. O nome da editora é obrigatório.</p></div><span className={`badge ${nameMapped?'green':'red'}`}>{nameMapped?'Nome mapeado':'Mapeie o nome'}</span></div><div className="mapping-grid">{headers.map((h,i)=><label key={`${h}-${i}`}><span>{h}</span><select value={mapping[i]||''} onChange={e=>setMap(i,e.target.value)}>{TARGETS.map(([k,v])=><option key={k||'ignore'} value={k}>{v}</option>)}</select></label>)}</div></section>
      <section className="card panel" style={{marginTop:16}}><div className="panel-head"><div><h2>3. Conferir prévia</h2><p>{valid.length.toLocaleString('pt-BR')} linhas válidas · {invalidCount} sem nome serão ignoradas.</p></div></div><div className="import-preview-wrap"><table className="data-table import-preview"><thead><tr>{mapping.map((key,i)=>key?<th key={`${key}-${i}`}>{TARGETS.find(([k])=>k===key)?.[1]||key}</th>:null)}</tr></thead><tbody>{transformed.slice(0,8).map((r,idx)=><tr key={idx}>{mapping.map((key,i)=>key?<td key={`${key}-${i}`}>{r[key]||'—'}</td>:null)}</tr>)}</tbody></table></div>{transformed.length>8&&<p className="muted import-preview-note">Mostrando 8 de {transformed.length.toLocaleString('pt-BR')} linhas.</p>}</section>
      <section className="card panel import-confirm" style={{marginTop:16}}><div><h2>4. Importar</h2><p>Quando houver uma editora com o mesmo CNPJ — ou mesmo nome e UF — escolha como tratar.</p></div><label>Duplicatas<select value={mode} onChange={e=>setMode(e.target.value)}><option value="skip">Ignorar e preservar o cadastro atual</option><option value="update">Atualizar campos preenchidos no CSV</option></select></label><button className="btn" disabled={busy||!nameMapped||!valid.length} onClick={runImport}>{busy?`Importando… ${progress}%`:<><Upload size={16}/> Importar {valid.length.toLocaleString('pt-BR')} editoras</>}</button>{busy&&<div className="import-progress"><div style={{width:`${progress}%`}}/></div>}</section>
    </>}
    {result&&<section className="card panel import-result" style={{marginTop:16}}><div className="panel-head"><div><h2>Resultado</h2><p>O Radar Score das editoras inseridas/atualizadas é recalculado automaticamente.</p></div><CheckCircle2 size={24}/></div><div className="import-result-grid"><Result label="Inseridas" value={result.inserted}/><Result label="Atualizadas" value={result.updated}/><Result label="Ignoradas" value={result.skipped}/><Result label="Erros" value={result.errors}/></div>{result.details?.length>0&&<div className="import-errors"><strong>Linhas com erro</strong>{result.details.slice(0,20).map((d,i)=><div key={i}>Linha {d.row}: {d.name||'sem nome'} — {d.error}</div>)}</div>}</section>}
  </div>
}
function Result({label,value}){return <div><span>{label}</span><strong>{Number(value||0).toLocaleString('pt-BR')}</strong></div>}
