'use client';
import { useEffect, useState } from 'react';
import { Check, Copy, MessageSquareText, Plus, X } from 'lucide-react';
import { useCrm } from '@/components/CrmProvider';
import ModalDialog from '@/components/ModalDialog';
import { CHANNEL_LABELS } from '@/lib/constants';

export default function Templates(){const {supabase,membership,user,isManager}=useCrm();const org=membership?.organization_id;const [rows,setRows]=useState([]);const [copied,setCopied]=useState('');const [show,setShow]=useState(false);const [notice,setNotice]=useState('');async function load(){if(!org)return;const {data}=await supabase.from('outreach_templates').select('*').eq('organization_id',org).eq('active',true).order('name');setRows(data||[])}useEffect(()=>{load()},[org]);async function copy(t){await navigator.clipboard.writeText(t.body);setCopied(t.id);setTimeout(()=>setCopied(''),1400)}return <div className="page-wrap"><div className="page-head"><div><div className="eyebrow">Biblioteca comercial</div><h1>Roteiros comerciais da Radar</h1><p>Mensagens para abrir conversas com editoras, apresentar o trabalho da Radar e conduzir oportunidades no mercado público.</p></div>{isManager&&<button className="btn" onClick={()=>setShow(true)}><Plus size={16}/> Novo modelo</button>}</div>{notice&&<div className="notice-bar"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}<div className="template-grid">{rows.map(t=><article className="card template-card" key={t.id}><div className="template-top"><div className="template-icon"><MessageSquareText/></div><div><strong>{t.name}</strong><span>{CHANNEL_LABELS[t.channel]||t.channel}{t.purpose?` · ${t.purpose}`:''}</span></div></div><div className="template-body">{t.body}</div><button className="btn secondary full" onClick={()=>copy(t)}>{copied===t.id?<><Check size={16}/> Copiado</>:<><Copy size={16}/> Copiar texto</>}</button></article>)}</div><div className="card panel manual-tip"><h3>Personalize antes de enviar</h3><p>Substitua os campos entre colchetes, como <code>[NOME]</code>, <code>[EDITORA]</code>, <code>[OPORTUNIDADE/REDE]</code> ou <code>[EDITAL/PROGRAMA]</code>. Ajuste o texto ao contexto real da conversa e registre no CRM o que foi enviado e qual é o próximo passo.</p></div>{show&&<TemplateModal org={org} user={user} supabase={supabase} onClose={()=>setShow(false)} onSaved={()=>{setShow(false);load();setNotice('Modelo criado.')}}/>}</div>}
function TemplateModal({org,user,supabase,onClose,onSaved}){const [f,setF]=useState({name:'',channel:'email',purpose:'',body:''});const [err,setErr]=useState('');const [busy,setBusy]=useState(false);function s(k,v){setF(x=>({...x,[k]:v}))}async function save(e){e.preventDefault();if(busy)return;setBusy(true);setErr('');const {error}=await supabase.from('outreach_templates').insert({organization_id:org,...f,created_by:user.id,updated_by:user.id});if(error){setErr(error.message);setBusy(false)}else onSaved()}return <ModalDialog title="Novo modelo" description="Crie um roteiro para a equipe usar nas próximas abordagens." onClose={onClose} onSubmit={save} busy={busy}>{err&&<div className="notice error" role="alert">{err}</div>}<div className="form-grid"><label className="span-2">Nome<input className="input" required value={f.name} onChange={e=>s('name',e.target.value)}/></label><label>Canal<select value={f.channel} onChange={e=>s('channel',e.target.value)}><option value="phone">Ligação</option><option value="email">E-mail</option><option value="whatsapp">WhatsApp</option><option value="linkedin">LinkedIn</option><option value="meeting">Reunião</option><option value="other">Outro</option></select></label><label>Finalidade<input className="input" value={f.purpose} onChange={e=>s('purpose',e.target.value)} placeholder="Primeiro contato, follow-up…"/></label><label className="span-2">Texto<textarea rows={8} required value={f.body} onChange={e=>s('body',e.target.value)}/></label></div><div className="modal-actions"><button type="button" className="btn secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="btn" disabled={busy}>{busy?'Salvando…':'Salvar modelo'}</button></div></ModalDialog>}
