import Link from 'next/link';
import { BookOpenCheck } from 'lucide-react';

const sections=[['inicio','Primeiros passos'],['prioridades','Prioridades e Score'],['editoras','Encontrar editoras'],['carteira','Assumir uma editora'],['contatos','Registrar contatos'],['tarefas','Fila e lembretes'],['cadencias','Cadências'],['pipeline','Pipeline'],['desempenho','Desempenho e metas'],['relatorios','Relatórios'],['anexos','Anexos'],['equipe','Perfis de acesso'],['faq','FAQ rápido']];
export default function ManualPage(){return <div className="page-wrap"><div className="page-head"><div><div className="eyebrow">Guia de uso</div><h1>Manual do CRM</h1><p>Como organizar a prospecção, registrar o histórico e trabalhar em equipe sem perder contexto.</p></div><BookOpenCheck size={28}/></div><div className="manual-layout"><nav className="card manual-nav">{sections.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><div className="manual-content">
<Section id="inicio" title="Primeiros passos"><p>O CRM funciona melhor quando cada contato deixa um histórico claro para a próxima pessoa que consultar a editora.</p><ol><li>Comece por <Link className="text-link" href="/app/prioridades">Prioridades</Link> para ver o que merece atenção agora, ou abra <Link className="text-link" href="/app/editoras">Editoras</Link> para pesquisar a base.</li><li>Veja se já existe responsável e consulte o histórico antes de fazer uma nova abordagem.</li><li>Se estiver sem responsável e você for trabalhar nela, clique em <b>Assumir</b>.</li><li>Depois de uma ligação, e-mail, reunião ou mensagem relevante, registre o contato.</li><li>Preencha o próximo passo e a próxima ação quando houver retorno combinado.</li></ol></Section>
<Section id="prioridades" title="Prioridades, próxima melhor ação e Radar Score"><p>A página <Link className="text-link" href="/app/prioridades">Prioridades</Link> organiza uma fila de trabalho usando regras do próprio CRM — não IA. Ela considera prazos, tarefas, responsabilidade, histórico e Radar Score para sugerir ações como primeiro contato, follow-up, retomada ou pesquisa de decisor.</p><p>Use <b>Entender</b> ao lado do Radar Score para ver os fatores que formaram a pontuação. Dados cadastrais, decisor identificado, sinais de interesse e resultados de contato podem aumentar ou reduzir o score.</p><p>A sugestão ajuda a ordenar o dia, mas o contexto comercial continua sendo a referência final.</p></Section>
<Section id="editoras" title="Encontrar editoras"><p>A tela <Link className="text-link" href="/app/editoras">Editoras</Link> é a base central. Você pode buscar por nome, nome fantasia ou CNPJ e combinar filtros de etapa, prioridade, UF, responsável, situação de contato e Radar Score.</p><p>Use <b>Visões salvas</b> para guardar combinações que você usa sempre. Exemplos: “Minha carteira”, “SP · nunca contatadas”, “Score 80+” ou “Sem responsável”. A visão fica salva somente no seu usuário.</p><p>Supervisores e administradores também têm acesso a <Link className="text-link" href="/app/qualidade">Qualidade da base</Link>, que aponta dados faltantes e possíveis duplicidades.</p></Section>
<Section id="carteira" title="Assumir uma editora"><p>Prospectadores não precisam esperar um administrador distribuir toda a base. Quando uma editora estiver <b>sem responsável</b>, você pode clicar em <b>Assumir</b> e ela passa a fazer parte da sua carteira.</p><ul><li>Você não consegue “tomar” uma editora que já esteja com outro prospectador.</li><li>Supervisores e administradores podem redistribuir contas quando necessário.</li><li>Use o filtro <b>Minha carteira</b> para ver somente as editoras sob sua responsabilidade.</li></ul></Section>
<Section id="contatos" title="Registrar contatos e interações"><p>Na ficha da editora, use <b>Registrar contato</b> depois de qualquer interação comercial relevante.</p><ul><li>Escolha o canal: ligação, e-mail, WhatsApp, LinkedIn, reunião etc.</li><li>Registre o resultado real da conversa.</li><li>No resumo, anote o que aconteceu de forma objetiva e útil para outra pessoa.</li><li>Preencha interesse, próximo passo e próxima ação quando fizer sentido.</li><li>Se informar uma <b>próxima ação com data</b>, o CRM cria automaticamente uma tarefa de follow-up para você.</li><li>Se descobrir uma pessoa importante, adicione-a em <b>Contatos</b> e marque como decisor quando aplicável.</li></ul></Section>
<Section id="tarefas" title="Minha fila e lembretes"><p>A <Link className="text-link" href="/app/tarefas">Minha fila</Link> reúne tarefas atribuídas a você. Use tarefas para ações concretas com prazo: ligar novamente, enviar apresentação, pesquisar contato, preparar proposta ou marcar reunião.</p><p>A página <Link className="text-link" href="/app/lembretes">Lembretes</Link> destaca tarefas atrasadas, tarefas das próximas 24 horas e próximas ações que estão chegando. Os alertas são internos: nada é enviado automaticamente para fora do CRM.</p></Section>
<Section id="cadencias" title="Cadências de prospecção"><p><Link className="text-link" href="/app/cadencias">Cadências</Link> organizam uma sequência de tentativas. Ao iniciar uma cadência, o CRM cria as tarefas nas datas previstas — por exemplo ligação hoje, e-mail em dois dias e nova tentativa depois.</p><p>A cadência <b>não envia a mensagem por você</b>. Ela organiza o trabalho; a abordagem continua sendo feita pela pessoa responsável e registrada no histórico.</p><p>Prospectadores podem iniciar cadências para si. Supervisores e administradores podem definir modelos e atribuir a sequência a outras pessoas.</p></Section>
<Section id="pipeline" title="Pipeline"><p>O <Link className="text-link" href="/app/pipeline">Pipeline</Link> representa a situação comercial atual de cada editora. Clique em uma etapa para ver as contas naquele estágio e mova a editora quando a situação realmente mudar.</p><p>Oportunidades são negócios específicos. Quando houver valor estimado, probabilidade e data prevista, esses dados alimentam o forecast comercial.</p></Section>
<Section id="desempenho" title="Desempenho, metas e forecast"><p>A página <Link className="text-link" href="/app/desempenho">Desempenho</Link> mostra sua carteira, interações, tarefas, oportunidades e metas. Supervisores e administradores também veem o painel consolidado da equipe.</p><p>O forecast usa as oportunidades abertas e sua probabilidade para mostrar o <b>valor ponderado</b>. Ele é uma estimativa de gestão, não uma garantia de receita.</p><p>As metas devem orientar consistência e avanço comercial; evite interpretar apenas volume de contatos como qualidade.</p></Section>
<Section id="relatorios" title="Relatórios"><p>A página <Link className="text-link" href="/app/relatorios">Relatórios</Link> mostra a base completa, cobertura de contatos, distribuição do pipeline, prioridades, oportunidades, tarefas e resultados recentes.</p><p>O botão <b>Exportar análise (.xlsx)</b> gera um arquivo com resumo executivo, leitura automática dos dados e a relação detalhada das editoras. Use o período de 30, 60 ou 90 dias para analisar atividade recente.</p></Section>
<Section id="anexos" title="Anexos"><p>Use <Link className="text-link" href="/app/anexos">Anexos</Link> para guardar propostas, apresentações, planilhas e outros arquivos vinculados a uma editora. Os documentos são privados e só podem ser abertos por usuários autenticados da equipe.</p><p>Evite anexar arquivos pessoais ou sem relação com a atividade comercial. O limite por arquivo é de 15 MB.</p></Section>
<Section id="equipe" title="Perfis de acesso"><ul><li><b>Prospectador:</b> consulta a base, assume editoras sem responsável, registra contatos, usa cadências, tarefas e anexos.</li><li><b>Supervisor:</b> faz o trabalho comercial e também pode acompanhar a equipe, metas, qualidade da base e redistribuir responsabilidades.</li><li><b>Administrador:</b> gerencia acessos, perfis, informações cadastrais e importações em massa.</li></ul><p>Administradores têm a página <b>Importar</b> para carregar CSVs com prévia e tratamento de duplicatas.</p></Section>
<Section id="faq" title="FAQ rápido"><Faq q="Por onde começo meu dia?">Abra <b>Prioridades</b>. A fila coloca tarefas vencidas, próximos passos e contas relevantes em uma ordem prática de trabalho.</Faq><Faq q="Posso trabalhar em uma editora que está sem responsável?">Sim. Clique em <b>Assumir</b>. Ela passa para sua carteira e você pode seguir a prospecção.</Faq><Faq q="Posso assumir uma editora que já está com outra pessoa?">Não como prospectador. Supervisor ou administrador pode fazer a redistribuição.</Faq><Faq q="Fiz uma ligação e ninguém atendeu. Preciso registrar?">Sim. Registrar “sem resposta” evita repetição sem contexto e também ajuda o Radar Score a refletir o histórico real.</Faq><Faq q="Informei uma data de retorno. Preciso criar outra tarefa manualmente?">Não necessariamente. Ao registrar uma interação com <b>próxima ação</b>, o CRM cria o follow-up automaticamente.</Faq><Faq q="A cadência envia e-mail ou WhatsApp sozinha?">Não. Ela cria e organiza tarefas. Você continua responsável por fazer a abordagem e registrar o resultado.</Faq><Faq q="O Radar Score usa IA?">Não. A pontuação é calculada por regras explícitas e você pode visualizar os fatores em <b>Entender</b>.</Faq><Faq q="Posso salvar meus filtros?">Sim. Monte os filtros em Editoras e use <b>Salvar visão</b>. A visão fica disponível no seu próprio usuário.</Faq></Section>
</div></div></div>}
function Section({id,title,children}){return <section id={id} className="card manual-section"><h2>{title}</h2>{children}</section>}
function Faq({q,children}){return <div style={{padding:'14px 0',borderTop:'1px solid #eef0f3'}}><strong>{q}</strong><p style={{marginBottom:0}}>{children}</p></div>}
