import Link from 'next/link';
import { BookOpenCheck } from 'lucide-react';

const sections=[['inicio','Primeiros passos'],['editoras','Encontrar editoras'],['carteira','Assumir uma editora'],['contatos','Registrar contatos'],['tarefas','Minha fila'],['pipeline','Pipeline'],['relatorios','Relatórios'],['equipe','Perfis de acesso'],['faq','FAQ rápido']];
export default function ManualPage(){return <div className="page-wrap"><div className="page-head"><div><div className="eyebrow">Guia de uso</div><h1>Manual do CRM</h1><p>Como organizar a prospecção, registrar o histórico e trabalhar em equipe sem perder contexto.</p></div><BookOpenCheck size={28}/></div><div className="manual-layout"><nav className="card manual-nav">{sections.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><div className="manual-content">
<Section id="inicio" title="Primeiros passos"><p>O CRM funciona melhor quando cada contato deixa um histórico claro para a próxima pessoa que consultar a editora.</p><ol><li>Abra <Link className="text-link" href="/app/editoras">Editoras</Link> e escolha uma conta para trabalhar.</li><li>Veja se já existe responsável e consulte o histórico antes de fazer uma nova abordagem.</li><li>Se estiver sem responsável e você for trabalhar nela, clique em <b>Assumir</b>.</li><li>Depois de uma ligação, e-mail, reunião ou mensagem relevante, registre o contato.</li><li>Defina o próximo passo e crie uma tarefa quando houver uma ação com prazo.</li></ol></Section>
<Section id="editoras" title="Encontrar editoras"><p>A tela <Link className="text-link" href="/app/editoras">Editoras</Link> é a base central. Você pode buscar por nome, nome fantasia ou CNPJ e combinar filtros de etapa, prioridade, UF, responsável, situação de contato e Radar Score.</p><p>Use <b>Visões salvas</b> para guardar combinações que você usa sempre. Exemplos: “Minha carteira”, “SP · nunca contatadas”, “Score 80+” ou “Sem responsável”. A visão fica salva somente no seu usuário.</p><p>O Radar Score ajuda a ordenar a atenção, mas não substitui o contexto: uma editora com score alto pode já estar sendo trabalhada por outra pessoa.</p></Section>
<Section id="carteira" title="Assumir uma editora"><p>Prospectadores não precisam esperar um administrador distribuir toda a base. Quando uma editora estiver <b>sem responsável</b>, você pode clicar em <b>Assumir</b> e ela passa a fazer parte da sua carteira.</p><ul><li>Você não consegue “tomar” uma editora que já esteja com outro prospectador.</li><li>Supervisores e administradores podem redistribuir contas quando necessário.</li><li>Use o filtro <b>Minha carteira</b> para ver somente as editoras sob sua responsabilidade.</li></ul></Section>
<Section id="contatos" title="Registrar contatos e interações"><p>Na ficha da editora, use <b>Registrar contato</b> depois de qualquer interação comercial relevante.</p><ul><li>Escolha o canal: ligação, e-mail, WhatsApp, LinkedIn, reunião etc.</li><li>Registre o resultado real da conversa.</li><li>No resumo, anote o que aconteceu de forma objetiva e útil para outra pessoa.</li><li>Preencha interesse, próximo passo e próxima ação quando fizer sentido.</li><li>Se descobrir uma pessoa importante, adicione-a em <b>Contatos</b> e marque como decisor quando aplicável.</li></ul><p>Mesmo quando não houve resposta, vale registrar o resultado. Isso evita abordagens repetidas e ajuda a medir a cadência comercial.</p></Section>
<Section id="tarefas" title="Minha fila e follow-ups"><p>A <Link className="text-link" href="/app/tarefas">Minha fila</Link> reúne tarefas atribuídas a você. Crie uma tarefa para ações concretas com prazo: ligar novamente, enviar apresentação, pesquisar um contato, preparar proposta ou marcar reunião.</p><p>Ao concluir, marque como feita. Tarefas atrasadas aparecem nos indicadores e ajudam a identificar follow-ups que precisam de atenção.</p></Section>
<Section id="pipeline" title="Pipeline"><p>O <Link className="text-link" href="/app/pipeline">Pipeline</Link> representa a situação comercial atual de cada editora. Clique em uma etapa para ver as contas naquele estágio e mova a editora quando a situação realmente mudar.</p><p>Não avance uma etapa apenas para “organizar a tela”: o relatório usa essas etapas para mostrar a distribuição real da operação.</p></Section>
<Section id="relatorios" title="Relatórios"><p>A página <Link className="text-link" href="/app/relatorios">Relatórios</Link> mostra a base completa, cobertura de contatos, distribuição do pipeline, prioridades, oportunidades, tarefas e resultados recentes.</p><p>O botão <b>Exportar análise (.xlsx)</b> gera um arquivo com resumo executivo, leitura automática dos dados e a relação detalhada das editoras. Use o período de 30, 60 ou 90 dias para analisar atividade recente.</p></Section>
<Section id="equipe" title="Perfis de acesso"><ul><li><b>Prospectador:</b> consulta a base, assume editoras sem responsável, registra contatos, cria tarefas e mantém o acompanhamento comercial.</li><li><b>Supervisor:</b> faz o trabalho comercial e também pode acompanhar a equipe e redistribuir responsabilidades.</li><li><b>Administrador:</b> gerencia acessos, perfis e informações cadastrais que exigem maior controle.</li></ul><p>Se você acabou de criar sua conta e ainda não consegue entrar, seu cadastro provavelmente está aguardando liberação por um administrador.</p></Section>
<Section id="faq" title="FAQ rápido"><Faq q="Posso trabalhar em uma editora que está sem responsável?">Sim. Clique em <b>Assumir</b>. Ela passa para sua carteira e você pode seguir a prospecção.</Faq><Faq q="Posso assumir uma editora que já está com outra pessoa?">Não como prospectador. Isso evita conflito de abordagem. Supervisor ou administrador pode fazer a redistribuição.</Faq><Faq q="Fiz uma ligação e ninguém atendeu. Preciso registrar?">Sim. Registrar “sem resposta” evita que outra pessoa repita a mesma tentativa sem contexto e melhora os indicadores de atividade.</Faq><Faq q="Quando devo criar uma tarefa?">Quando existir uma ação futura concreta com prazo: retorno, follow-up, proposta, pesquisa ou reunião.</Faq><Faq q="Qual a diferença entre etapa e prioridade?">A etapa mostra <b>onde a editora está no processo</b>; a prioridade indica <b>quanta atenção ela merece</b> dentro da operação.</Faq><Faq q="O Radar Score decide quem eu devo contatar?">Não sozinho. Ele ajuda a ordenar a base, mas histórico, responsável, etapa e contexto comercial devem ser considerados juntos.</Faq><Faq q="Posso salvar meus filtros?">Sim. Monte os filtros na tela de Editoras e use <b>Salvar visão</b>. A visão fica disponível no seu próprio usuário.</Faq></Section>
</div></div></div>}
function Section({id,title,children}){return <section id={id} className="card manual-section"><h2>{title}</h2>{children}</section>}
function Faq({q,children}){return <div style={{padding:'14px 0',borderTop:'1px solid #eef0f3'}}><strong>{q}</strong><p style={{marginBottom:0}}>{children}</p></div>}
