import Link from 'next/link';
import { BookOpenCheck } from 'lucide-react';

const sections=[['inicio','Primeiros passos'],['prioridades','Prioridades e Score'],['editoras','Encontrar editoras'],['carteira','Assumir uma editora'],['contatos','Registrar contatos'],['tarefas','Fila e lembretes'],['cadencias','Cadências'],['pipeline','Pipeline'],['desempenho','Desempenho e metas'],['relatorios','Relatórios'],['anexos','Anexos'],['equipe','Perfis de acesso'],['faq','FAQ rápido']];
export default function ManualPage(){return <div className="page-wrap"><div className="page-head"><div><div className="eyebrow">Guia de uso</div><h1>Manual do CRM</h1><p>Como organizar a prospecção, registrar o histórico e trabalhar em equipe sem perder contexto.</p></div><BookOpenCheck size={28}/></div><div className="manual-layout"><nav className="card manual-nav">{sections.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><div className="manual-content">
<Section id="inicio" title="Primeiros passos"><p>O CRM funciona melhor quando cada contato deixa um histórico claro para a próxima pessoa que consultar a editora.</p><ol><li>Comece por <Link className="text-link" href="/app/prioridades">Prioridades</Link> para ver o que merece atenção agora, ou abra <Link className="text-link" href="/app/editoras">Editoras</Link> para pesquisar a base.</li><li>Veja se já existe responsável e consulte o histórico antes de fazer uma nova abordagem.</li><li>Se estiver sem responsável e você for trabalhar nela, clique em <b>Assumir</b>.</li><li>Depois de uma ligação, e-mail, reunião ou mensagem relevante, registre o contato.</li><li>Preencha o próximo passo e a próxima ação quando houver retorno combinado.</li></ol></Section>
<Section id="prioridades" title="Prioridades, próxima melhor ação e Radar Score"><p>A página <Link className="text-link" href="/app/prioridades">Prioridades</Link> organiza uma fila de trabalho usando regras do próprio CRM — não IA. Ela considera prazos, tarefas, responsabilidade, histórico e Radar Score para sugerir ações como primeiro contato, follow-up, retomada ou pesquisa de decisor.</p><p>Use <b>Entender</b> ao lado do Radar Score para ver os fatores que formaram a pontuação. Dados cadastrais, decisor identificado, sinais de interesse e resultados de contato podem aumentar ou reduzir o score.</p><p>A sugestão ajuda a ordenar o dia, mas o contexto comercial continua sendo a referência final.</p></Section>
<Section id="editoras" title="Encontrar editoras"><p>A tela <Link className="text-link" href="/app/editoras">Editoras</Link> é a base central. Você pode buscar por nome, nome fantasia ou CNPJ e combinar filtros de etapa, prioridade, UF, responsável, situação de contato e Radar Score.</p><p>Use <b>Visões salvas</b> para guardar combinações que você usa sempre. Exemplos: “Minha carteira”, “SP · nunca contatadas”, “Score 80+” ou “Sem responsável”. A visão fica salva somente no seu usuário.</p><p>Supervisores e administradores também têm acesso a <Link className="text-link" href="/app/qualidade">Qualidade da base</Link>, que aponta dados faltantes e possíveis duplicidades.</p></Section>
<Section id="carteira" title="Assumir uma editora"><p>Prospectadores não precisam esperar um administrador distribuir toda a base. Quando uma editora estiver <b>sem responsável</b>, você pode clicar em <b>Assumir</b> e ela passa a fazer parte da sua carteira.</p><ul><li>Você não consegue “tomar” uma editora que já esteja com outro prospectador.</li><li>Supervisores e administradores podem redistribuir contas quando necessário.</li><li>Use o filtro <b>Minha carteira</b> para ver somente as editoras sob sua responsabilidade.</li></ul></Section>
<Section id="contatos" title="Registrar contatos e interações"><p>Na ficha da editora, use <b>Registrar contato</b> depois de qualquer interação comercial relevante. Prospectadores registram e alteram o acompanhamento das editoras sob sua responsabilidade; o histórico das demais editoras continua visível como contexto.</p><ul><li>Escolha o canal: ligação, e-mail, WhatsApp, LinkedIn, reunião etc.</li><li>Registre o resultado real da conversa.</li><li>No resumo, anote o que aconteceu de forma objetiva e útil para outra pessoa.</li><li>Preencha interesse, próximo passo e próxima ação quando fizer sentido.</li><li>Se informar uma <b>próxima ação com data</b>, o CRM cria automaticamente uma tarefa de follow-up para você.</li><li>Se descobrir uma pessoa importante, adicione-a em <b>Contatos</b> e marque como decisor quando aplicável.</li></ul></Section>
<Section id="tarefas" title="Minha fila e lembretes"><p>A <Link className="text-link" href="/app/tarefas">Minha fila</Link> reúne tarefas atribuídas a você. Supervisores e administradores podem alternar para uma visão da equipe; prospectadores veem apenas suas próprias tarefas.</p><p>A página <Link className="text-link" href="/app/lembretes">Lembretes</Link> destaca suas tarefas atrasadas, tarefas das próximas 24 horas e próximas ações que estão chegando.</p></Section>
<Section id="cadencias" title="Cadências de prospecção"><p><Link className="text-link" href="/app/cadencias">Cadências</Link> organizam uma sequência de tentativas. Ao iniciar uma cadência, o CRM cria as tarefas nas datas previstas — por exemplo ligação hoje, e-mail em dois dias e nova tentativa depois.</p><p>Prospectadores acompanham suas próprias cadências. Supervisores e administradores podem acompanhar a equipe, definir modelos e atribuir sequências a outras pessoas.</p></Section>
<Section id="pipeline" title="Pipeline"><p>O <Link className="text-link" href="/app/pipeline">Pipeline</Link> representa a situação comercial atual. Prospectadores veem o pipeline da própria carteira; supervisores e administradores veem a distribuição da equipe.</p><p>Oportunidades são negócios específicos. Quando houver valor estimado, probabilidade e data prevista, esses dados alimentam o forecast comercial.</p></Section>
<Section id="desempenho" title="Desempenho, metas e forecast"><p>A página <Link className="text-link" href="/app/desempenho">Desempenho</Link> mostra sua carteira, interações, tarefas, oportunidades, metas e forecast. Para prospectadores, esses indicadores são pessoais. Supervisores e administradores também veem o painel e o forecast consolidados da equipe.</p><p>O forecast usa as oportunidades abertas e sua probabilidade para mostrar o <b>valor ponderado</b>. Ele é uma estimativa de gestão, não uma garantia de receita.</p></Section>
<Section id="relatorios" title="Relatórios"><p>A página <Link className="text-link" href="/app/relatorios">Relatórios</Link> acompanha pipeline, prioridades, contatos, oportunidades e tarefas. Prospectadores recebem uma visão da própria carteira e atividade; supervisores e administradores recebem a visão da operação inteira.</p><p>O botão <b>Exportar análise (.xlsx)</b> respeita o mesmo escopo: o prospectador exporta a própria carteira e a gestão pode exportar a base completa.</p></Section>
<Section id="anexos" title="Anexos"><p>Use <Link className="text-link" href="/app/anexos">Anexos</Link> para guardar propostas, apresentações, planilhas e outros arquivos vinculados a uma editora. Prospectadores trabalham com arquivos da própria carteira; a gestão pode consultar os documentos da equipe.</p><p>Evite anexar arquivos pessoais ou sem relação com a atividade comercial. O limite por arquivo é de 15 MB.</p></Section>
<Section id="equipe" title="Perfis de acesso"><ul><li><b>Prospectador:</b> trabalha a própria carteira, fila, cadências, pipeline, desempenho, relatórios e anexos; continua podendo consultar a base e o histórico das editoras para ter contexto.</li><li><b>Supervisor:</b> tem o trabalho pessoal e também a visão consolidada da equipe, metas, qualidade da base e redistribuição de responsabilidades.</li><li><b>Administrador:</b> tem toda a visão de gestão e ainda controla acessos, perfis, informações cadastrais e importações em massa.</li></ul><p>O menu acompanha essa divisão: trabalho diário aparece primeiro, gestão vem depois e funções administrativas aparecem somente para quem precisa delas.</p></Section>
<Section id="faq" title="FAQ rápido"><Faq q="Por onde começo meu dia?">Abra <b>Prioridades</b>. A fila coloca tarefas vencidas, próximos passos e contas relevantes em uma ordem prática de trabalho.</Faq><Faq q="Posso trabalhar em uma editora que está sem responsável?">Sim. Clique em <b>Assumir</b>. Ela passa para sua carteira e você pode seguir a prospecção.</Faq><Faq q="Posso assumir uma editora que já está com outra pessoa?">Não como prospectador. Supervisor ou administrador pode fazer a redistribuição.</Faq><Faq q="Consigo ver tarefas ou metas de outro prospectador?">Como prospectador, não. Supervisor e administrador têm as visões consolidadas da equipe.</Faq><Faq q="Ainda consigo consultar uma editora que pertence a outra pessoa?">Sim. A base e o histórico de contatos continuam disponíveis como contexto, mas as ações comerciais ficam protegidas pela responsabilidade da conta.</Faq><Faq q="Informei uma data de retorno. Preciso criar outra tarefa manualmente?">Não necessariamente. Ao registrar uma interação com <b>próxima ação</b>, o CRM cria o follow-up automaticamente.</Faq><Faq q="O Radar Score usa IA?">Não. A pontuação é calculada por regras explícitas e você pode visualizar os fatores em <b>Entender</b>.</Faq><Faq q="Posso salvar meus filtros?">Sim. Monte os filtros em Editoras e use <b>Salvar visão</b>. A visão fica disponível no seu próprio usuário.</Faq></Section>
</div></div></div>}
function Section({id,title,children}){return <section id={id} className="card manual-section"><h2>{title}</h2>{children}</section>}
function Faq({q,children}){return <div style={{padding:'14px 0',borderTop:'1px solid #eef0f3'}}><strong>{q}</strong><p style={{marginBottom:0}}>{children}</p></div>}
