'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Building2, CheckCircle2, Clock3, Globe2, Mail, MapPin, MessageSquareText, Phone, Plus, Save, Target, UserRound, X } from 'lucide-react';
import { useCrm } from '@/components/CrmProvider';
import { CHANNEL_LABELS, INTEREST_LABELS, PRIORITY_LABELS, RESULT_LABELS, TASK_TYPE_LABELS, currency, formatDate } from '@/lib/constants';

function localInput(value){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return'';const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}

export default function PublisherDetailPage(){
  const {id}=useParams(); const {supabase,membership,user,teamMap,team,isManager,activityVersion}=useCrm(); const org=membership?.organization_id;
  const [publisher,setPublisher]=useState(null); const [contacts,setContacts]=useState([]); const [interactions,setInteractions]=useState([]); const [tasks,setTasks]=useState([]); const [opps,setOpps]=useState([]); const [stages,setStages]=useState([]);
  const [loading,setLoading]=useState(true); const [notice,setNotice]=useState(''); const [modal,setModal]=useState(''); const [edit,setEdit]=useState({priority:'medium',stage_id:'',owner_user_id:'',next_action_at:'',notes:''});
  async function load(){if(!org||!id)return;setLoading(true);const [p,c,i,t,o,s]=await Promise.all([
    supabase.from('publishers').select('*').eq('organization_id',org).eq('id',id).maybeSingle(),
    supabase.from('contacts').select('*').eq('organization_id',org).eq('publisher_id',id).eq('active',true).order('is_decision_maker',{ascending:false}).order('full_name'),
    supabase.from('interactions').select('*').eq('organization_id',org).eq('publisher_id',id).order('occurred_at',{ascending:false}).limit(30),
    supabase.from('tasks').select('*').eq('organization_id',org).eq('publisher_id',id).order('due_at',{ascending:true,nullsFirst:false}).limit(30),
    supabase.from('opportunities').select('*').eq('organization_id',org).eq('publisher_id',id).order('created_at',{ascending:false}),
    supabase.from('pipeline_stages').select('id,name,position,stage_type').eq('organization_id',org).eq('active',true).order('position')
  ]);if(p.error)setNotice(p.error.message);setPublisher(p.data||null);setContacts(c.data||[]);setInteractions(i.data||[]);setTasks(t.data||[]);setOpps(o.data||[]);setStages(s.data||[]);if(p.data)setEdit({priority:p.data.priority||'medium',stage_id:p.data.stage_id||'',owner_user_id:p.data.owner_user_id||'',next_action_at:localInput(p.data.next_action_at),notes:p.data.notes||''});setLoading(false)}
  useEffect(()=>{load()},[org,id,activityVersion]);
  const stageMap=useMemo(()=>Object.fromEntries(stages.map(s=>[s.id,s])),[stages]);
  const canWork=Boolean(publisher&&(isManager||publisher.owner_user_id===user?.id));
  const unassigned=Boolean(publisher&&!publisher.owner_user_id);
  const ownerName=publisher?.owner_user_id?(teamMap[publisher.owner_user_id]?.full_name||teamMap[publisher.owner_user_id]?.email||'Outra pessoa da equipe'):'Sem responsável';
  async function claimPublisher(){if(!publisher||isManager||publisher.owner_user_id||!user?.id)return;const {error}=await supabase.from('publishers').update({owner_user_id:user.id,updated_by:user.id,updated_at:new Date().toISOString()}).eq('organization_id',org).eq('id',publisher.id).is('owner_user_id',null);if(error)setNotice(error.message);else{setNotice(`Você assumiu ${publisher.name}.`);load()}}
  async function saveCommercial(){if(!publisher||!canWork)return;const {error}=await supabase.from('publishers').update({priority:edit.priority,stage_id:edit.stage_id||null,owner_user_id:isManager?(edit.owner_user_id||null):user.id,next_action_at:edit.next_action_at?new Date(edit.next_action_at).toISOString():null,notes:edit.notes||null,updated_by:user?.id||null,updated_at:new Date().toISOString()}).eq('organization_id',org).eq('id',publisher.id);setNotice(error?error.message:'Dados comerciais atualizados.');if(!error)load()}
  async function doneTask(task){if(!canWork)return;const {error}=await supabase.from('tasks').update({status:'done',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('organization_id',org).eq('id',task.id);if(error)setNotice(error.message);else load()}
  if(loading)return <div className="page-wrap"><div className="table-empty">Carregando editora…</div></div>;
  if(!publisher)return <div className="page-wrap"><Link href="/app/editoras" className="text-link"><ArrowLeft size={15}/> Voltar</Link><div className="card panel" style={{marginTop:16}}><h2>Editora não encontrada</h2><p className="muted">Ela pode ter sido arquivada ou você não tem acesso a esse registro.</p></div></div>;
  return <div className="page-wrap">
    <div className="page-head"><div><Link href="/app/editoras" className="text-link"><ArrowLeft size={15}/> Editoras</Link><div className="eyebrow" style={{marginTop:12}}>Ficha comercial</div><h1>{publisher.name}</h1><p>{[publisher.trade_name,publisher.city,publisher.state].filter(Boolean).join(' · ')||'Dados cadastrais e histórico comercial.'}</p></div><div className="chips"><span className="badge dark">Score {publisher.score??0}</span><span className="badge">{stageMap[publisher.stage_id]?.name||'Sem etapa'}</span></div></div>
    {notice&&<div className="notice-bar"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {!canWork&&!isManager&&<div className="notice-bar" style={{marginBottom:16}}><span>{unassigned?'Esta editora ainda está sem responsável. Assuma a conta para registrar contatos, tarefas e alterações comerciais.':`Esta editora está sob responsabilidade de ${ownerName}. Você pode consultar os dados e o histórico, mas o acompanhamento comercial fica em modo leitura.`}</span>{unassigned&&<button className="btn small" onClick={claimPublisher}>Assumir editora</button>}</div>}
    <div className="detail-grid"><div className="detail-stack">
      <section className="card panel"><div className="section-title"><h2>Dados da editora</h2></div><div className="info-grid"><Info label="Razão social" value={publisher.legal_name||publisher.trade_name}/><Info label="CNPJ" value={publisher.cnpj}/><Info label="Localização" value={[publisher.address_street,publisher.address_number,publisher.city,publisher.state].filter(Boolean).join(', ')}/><Info label="Perfil" value={publisher.profile}/><Info label="Segmentos" value={(publisher.genres||[]).join(', ')}/><Info label="Porte" value={publisher.company_size||publisher.size_label}/></div><div className="publisher-meta" style={{marginTop:16}}>{publisher.website&&<a className="text-link" href={publisher.website.startsWith('http')?publisher.website:`https://${publisher.website}`} target="_blank" rel="noreferrer"><Globe2 size={14}/>{publisher.website}</a>}{publisher.general_email&&<a className="text-link" href={`mailto:${publisher.general_email}`}><Mail size={14}/>{publisher.general_email}</a>}{publisher.phone&&<span><Phone size={13}/> {publisher.phone}</span>}</div></section>
      <section className="card panel"><div className="section-title"><div><h2>Contatos</h2><p className="muted">Pessoas vinculadas à editora.</p></div>{canWork&&<button className="btn secondary small" onClick={()=>setModal('contact')}><Plus size={14}/> Contato</button>}</div>{contacts.length?contacts.map(c=><div className="contact-row" key={c.id}><strong>{c.full_name}{c.is_decision_maker?' · Decisor':''}</strong><span>{[c.job_title,c.department].filter(Boolean).join(' · ')||'Sem cargo informado'}</span><span>{[c.email,c.mobile||c.phone].filter(Boolean).join(' · ')}</span></div>):<p className="muted">Nenhum contato cadastrado.</p>}</section>
      <section className="card panel"><div className="section-title"><div><h2>Histórico de contatos</h2><p className="muted">Interações mais recentes primeiro.</p></div>{canWork&&<button className="btn small" onClick={()=>setModal('interaction')}><Plus size={14}/> Registrar contato</button>}</div>{interactions.length?<div className="timeline">{interactions.map(i=><div className="timeline-item" key={i.id}><div className="timeline-dot"/><div className="timeline-body"><strong>{CHANNEL_LABELS[i.channel]||i.channel} · {RESULT_LABELS[i.result]||i.result||'Contato'}</strong><p>{i.summary}</p>{i.next_step&&<p><b>Próximo passo:</b> {i.next_step}</p>}<small>{formatDate(i.occurred_at,true)} · {teamMap[i.user_id]?.full_name||teamMap[i.user_id]?.email||'Equipe'}</small></div></div>)}</div>:<p className="muted">Ainda não há interações registradas.</p>}</section>
      <section className="card panel"><div className="section-title"><div><h2>Oportunidades</h2><p className="muted">Negócios relacionados a esta editora.</p></div></div>{opps.length?opps.map(o=><div className="opportunity-row" key={o.id}><strong>{o.title}</strong><div className="publisher-meta"><span>{o.stage}</span><span>{currency(o.estimated_value)}</span><span>{o.probability!=null?`${o.probability}%`:''}</span></div></div>):<p className="muted">Nenhuma oportunidade cadastrada.</p>}</section>
    </div><aside className="detail-stack">
      {canWork?<section className="card panel"><div className="section-title"><h3>Acompanhamento</h3></div><label>Etapa<select value={edit.stage_id} onChange={e=>setEdit(x=>({...x,stage_id:e.target.value}))}><option value="">Sem etapa</option>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label style={{marginTop:12}}>Prioridade<select value={edit.priority} onChange={e=>setEdit(x=>({...x,priority:e.target.value}))}>{Object.entries(PRIORITY_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{isManager?<label style={{marginTop:12}}>Responsável<select value={edit.owner_user_id} onChange={e=>setEdit(x=>({...x,owner_user_id:e.target.value}))}><option value="">Sem responsável</option>{team.filter(m=>m.active).map(m=><option value={m.user_id} key={m.user_id}>{m.full_name||m.email}</option>)}</select></label>:<div className="info-item" style={{marginTop:12}}><small>Responsável</small><span>Você</span></div>}<label style={{marginTop:12}}>Próxima ação<input type="datetime-local" className="input" value={edit.next_action_at} onChange={e=>setEdit(x=>({...x,next_action_at:e.target.value}))}/></label><label style={{marginTop:12}}>Notas<textarea rows={5} value={edit.notes} onChange={e=>setEdit(x=>({...x,notes:e.target.value}))}/></label><button className="btn full" style={{marginTop:14}} onClick={saveCommercial}><Save size={15}/> Salvar acompanhamento</button></section>:<section className="card panel"><div className="section-title"><h3>Acompanhamento</h3></div><div className="stat-list"><div className="stat-row"><span>Etapa</span><strong>{stageMap[publisher.stage_id]?.name||'Sem etapa'}</strong></div><div className="stat-row"><span>Prioridade</span><strong>{PRIORITY_LABELS[publisher.priority]||publisher.priority||'—'}</strong></div><div className="stat-row"><span>Responsável</span><strong>{ownerName}</strong></div><div className="stat-row"><span>Próxima ação</span><strong>{formatDate(publisher.next_action_at,true)}</strong></div></div>{publisher.notes&&<div style={{marginTop:14}}><small className="muted">Notas</small><p style={{marginBottom:0}}>{publisher.notes}</p></div>}</section>}
      <section className="card panel"><div className="section-title"><div><h3>Tarefas</h3><p className="muted">Pendências ligadas à editora.</p></div>{canWork&&<button className="icon-btn" onClick={()=>setModal('task')} title="Nova tarefa"><Plus size={16}/></button>}</div>{tasks.filter(t=>t.status!=='done'&&t.status!=='cancelled').length?tasks.filter(t=>t.status!=='done'&&t.status!=='cancelled').map(t=><div className="task-row" key={t.id}>{canWork?<button className="task-check" onClick={()=>doneTask(t)}><CheckCircle2 size={18}/></button>:<CheckCircle2 size={18} style={{color:'#98a2b3'}}/>}<div className="task-main"><strong>{t.title}</strong><span>{TASK_TYPE_LABELS[t.task_type]||t.task_type}</span></div><div className={`task-due ${t.due_at&&new Date(t.due_at)<new Date()?'late':''}`}><Clock3 size={13}/>{formatDate(t.due_at,true)}</div></div>):<p className="muted">Sem tarefas abertas.</p>}</section>
      <section className="card panel"><div className="section-title"><h3>Resumo</h3></div><div className="stat-list"><div className="stat-row"><span>Último contato</span><strong>{formatDate(publisher.last_contact_at,true)}</strong></div><div className="stat-row"><span>Próxima ação</span><strong>{formatDate(publisher.next_action_at,true)}</strong></div><div className="stat-row"><span>Temperatura</span><strong>{publisher.commercial_temperature||'—'}</strong></div><div className="stat-row"><span>Contatos</span><strong>{contacts.length}</strong></div></div></section>
    </aside></div>
    {canWork&&modal==='contact'&&<ContactModal supabase={supabase} org={org} publisher={publisher} user={user} onClose={()=>setModal('')} onSaved={()=>{setModal('');setNotice('Contato criado.');load()}}/>}
    {canWork&&modal==='interaction'&&<InteractionModal supabase={supabase} org={org} publisher={publisher} user={user} onClose={()=>setModal('')} onSaved={()=>{setModal('');setNotice('Interação registrada.');load()}}/>}
    {canWork&&modal==='task'&&<TaskModal supabase={supabase} org={org} publisher={publisher} user={user} onClose={()=>setModal('')} onSaved={()=>{setModal('');setNotice('Tarefa criada.');load()}}/>}
  </div>;
}

function Info({label,value}){return <div className="info-item"><small>{label}</small><span>{value||'—'}</span></div>}
function ContactModal({supabase,org,publisher,user,onClose,onSaved}){const [f,setF]=useState({full_name:'',job_title:'',department:'',email:'',phone:'',mobile:'',is_decision_maker:false});const [err,setErr]=useState('');async function save(e){e.preventDefault();const {error}=await supabase.from('contacts').insert({organization_id:org,publisher_id:publisher.id,...f,active:true,created_by:user?.id||null,updated_by:user?.id||null});if(error)setErr(error.message);else onSaved()}return <Modal title="Novo contato" onClose={onClose} onSubmit={save} err={err}><label className="span-2">Nome<input required className="input" value={f.full_name} onChange={e=>setF(x=>({...x,full_name:e.target.value}))}/></label><label>Cargo<input className="input" value={f.job_title} onChange={e=>setF(x=>({...x,job_title:e.target.value}))}/></label><label>Área<input className="input" value={f.department} onChange={e=>setF(x=>({...x,department:e.target.value}))}/></label><label>E-mail<input type="email" className="input" value={f.email} onChange={e=>setF(x=>({...x,email:e.target.value}))}/></label><label>Celular<input className="input" value={f.mobile} onChange={e=>setF(x=>({...x,mobile:e.target.value}))}/></label><label className="span-2"><span><input type="checkbox" checked={f.is_decision_maker} onChange={e=>setF(x=>({...x,is_decision_maker:e.target.checked}))}/> É decisor(a)</span></label></Modal>}
function InteractionModal({supabase,org,publisher,user,onClose,onSaved}){const [f,setF]=useState({channel:'phone',result:'connected',summary:'',interest_level:'',next_step:'',next_action_at:''});const [err,setErr]=useState('');async function save(e){e.preventDefault();const payload={organization_id:org,publisher_id:publisher.id,user_id:user?.id||null,occurred_at:new Date().toISOString(),channel:f.channel,direction:'outbound',result:f.result||null,summary:f.summary,interest_level:f.interest_level||null,next_step:f.next_step||null,next_action_at:f.next_action_at?new Date(f.next_action_at).toISOString():null};const {error}=await supabase.from('interactions').insert(payload);if(error)setErr(error.message);else onSaved()}return <Modal title="Registrar contato" onClose={onClose} onSubmit={save} err={err}><label>Canal<select value={f.channel} onChange={e=>setF(x=>({...x,channel:e.target.value}))}>{Object.entries(CHANNEL_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Resultado<select value={f.result} onChange={e=>setF(x=>({...x,result:e.target.value}))}>{Object.entries(RESULT_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="span-2">Resumo<textarea required rows={4} value={f.summary} onChange={e=>setF(x=>({...x,summary:e.target.value}))}/></label><label>Interesse<select value={f.interest_level} onChange={e=>setF(x=>({...x,interest_level:e.target.value}))}><option value="">Não informado</option>{Object.entries(INTEREST_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Próxima ação<input type="datetime-local" className="input" value={f.next_action_at} onChange={e=>setF(x=>({...x,next_action_at:e.target.value}))}/></label><label className="span-2">Próximo passo<input className="input" value={f.next_step} onChange={e=>setF(x=>({...x,next_step:e.target.value}))}/></label></Modal>}
function TaskModal({supabase,org,publisher,user,onClose,onSaved}){const [f,setF]=useState({title:'',task_type:'follow_up',priority:'medium',due_at:''});const [err,setErr]=useState('');async function save(e){e.preventDefault();const {error}=await supabase.from('tasks').insert({organization_id:org,publisher_id:publisher.id,assigned_to:user?.id||null,created_by:user?.id||null,title:f.title,task_type:f.task_type,priority:f.priority,status:'open',due_at:f.due_at?new Date(f.due_at).toISOString():null});if(error)setErr(error.message);else onSaved()}return <Modal title="Nova tarefa" onClose={onClose} onSubmit={save} err={err}><label className="span-2">Título<input required className="input" value={f.title} onChange={e=>setF(x=>({...x,title:e.target.value}))}/></label><label>Tipo<select value={f.task_type} onChange={e=>setF(x=>({...x,task_type:e.target.value}))}>{Object.entries(TASK_TYPE_LABELS).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Prioridade<select value={f.priority} onChange={e=>setF(x=>({...x,priority:e.target.value}))}>{Object.entries(PRIORITY_LABELS).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label className="span-2">Prazo<input type="datetime-local" className="input" value={f.due_at} onChange={e=>setF(x=>({...x,due_at:e.target.value}))}/></label></Modal>}
function Modal({title,onClose,onSubmit,err,children}){return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><div className="modal-head"><div><h3>{title}</h3></div><button type="button" onClick={onClose}><X/></button></div>{err&&<div className="notice error">{err}</div>}<div className="form-grid">{children}</div><div className="modal-actions"><button className="btn secondary" type="button" onClick={onClose}>Cancelar</button><button className="btn">Salvar</button></div></form></div>}
