'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Building2, MapPin, Plus, Search, X } from 'lucide-react';
import { useCrm } from '@/components/CrmProvider';
import Pagination from '@/components/Pagination';
import { PRIORITY_LABELS, formatDate } from '@/lib/constants';

const PAGE_SIZE = 40;

export default function PublishersPage(){
  const {supabase,membership,user,teamMap,isManager}=useCrm();
  const org=membership?.organization_id;
  const [rows,setRows]=useState([]); const [stages,setStages]=useState([]); const [count,setCount]=useState(0);
  const [page,setPage]=useState(1); const [q,setQ]=useState(''); const [stage,setStage]=useState(''); const [priority,setPriority]=useState('');
  const [loading,setLoading]=useState(true); const [showNew,setShowNew]=useState(false); const [notice,setNotice]=useState('');
  async function load(){if(!org)return;setLoading(true);let query=supabase.from('publishers').select('id,name,trade_name,cnpj,city,state,priority,score,stage_id,owner_user_id,last_contact_at,next_action_at,commercial_temperature',{count:'exact'}).eq('organization_id',org).eq('archived',false);if(q.trim())query=query.ilike('name',`%${q.trim()}%`);if(stage)query=query.eq('stage_id',stage);if(priority)query=query.eq('priority',priority);query=query.order('score',{ascending:false,nullsFirst:false}).order('name').range((page-1)*PAGE_SIZE,page*PAGE_SIZE-1);const [{data,error,count:total},{data:stageRows}]=await Promise.all([query,supabase.from('pipeline_stages').select('id,name,position,stage_type').eq('organization_id',org).eq('active',true).order('position')]);if(error)setNotice(error.message);setRows(data||[]);setCount(total||0);setStages(stageRows||[]);setLoading(false)}
  useEffect(()=>{const t=setTimeout(()=>load(),q?250:0);return()=>clearTimeout(t)},[org,page,stage,priority,q]);
  const stageMap=useMemo(()=>Object.fromEntries(stages.map(s=>[s.id,s])),[stages]);
  const totalPages=Math.max(1,Math.ceil(count/PAGE_SIZE));
  function reset(){setQ('');setStage('');setPriority('');setPage(1)}
  return <div className="page-wrap">
    <div className="page-head"><div><div className="eyebrow">Base comercial</div><h1>Editoras</h1><p>Consulte a base, o Radar Score, a etapa atual e o histórico de cada editora.</p></div>{isManager&&<button className="btn" onClick={()=>setShowNew(true)}><Plus size={16}/> Nova editora</button>}</div>
    {notice&&<div className="notice-bar"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    <div className="toolbar"><div className="search-box"><Search size={17}/><input className="input" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Buscar por nome da editora"/></div><select className="filter-select" value={stage} onChange={e=>{setStage(e.target.value);setPage(1)}}><option value="">Todas as etapas</option>{stages.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><select className="filter-select" value={priority} onChange={e=>{setPriority(e.target.value);setPage(1)}}><option value="">Todas as prioridades</option>{Object.entries(PRIORITY_LABELS).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select>{(q||stage||priority)&&<button className="btn secondary" onClick={reset}>Limpar</button>}</div>
    <section className="card table-card"><table className="data-table"><thead><tr><th>Editora</th><th>Local</th><th>Etapa</th><th>Prioridade</th><th>Score</th><th>Responsável</th><th>Último contato</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><div className="cell-main"><Link className="row-link" href={`/app/editoras/${p.id}`}>{p.name}</Link><span>{p.trade_name||p.cnpj||'—'}</span></div></td><td>{[p.city,p.state].filter(Boolean).join(' / ')||'—'}</td><td><span className="badge">{stageMap[p.stage_id]?.name||'Sem etapa'}</span></td><td><span className={`badge ${p.priority==='urgent'||p.priority==='high'?'red':p.priority==='medium'?'amber':''}`}>{PRIORITY_LABELS[p.priority]||p.priority||'—'}</span></td><td><strong>{p.score??0}</strong></td><td>{teamMap[p.owner_user_id]?.full_name||teamMap[p.owner_user_id]?.email||'—'}</td><td>{formatDate(p.last_contact_at,true)}</td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="table-empty"><Building2 size={30}/><p>Nenhuma editora encontrada com esses filtros.</p></div>}{loading&&<div className="table-empty">Carregando editoras…</div>}<Pagination page={page} totalPages={totalPages} onChange={setPage}/></section>
    {showNew&&<NewPublisherModal supabase={supabase} org={org} user={user} stages={stages} onClose={()=>setShowNew(false)} onSaved={()=>{setShowNew(false);setNotice('Editora criada.');setPage(1);load()}}/>}
  </div>;
}

function NewPublisherModal({supabase,org,user,stages,onClose,onSaved}){const [f,setF]=useState({name:'',trade_name:'',cnpj:'',city:'',state:'',website:'',general_email:'',phone:'',priority:'medium',stage_id:''});const [busy,setBusy]=useState(false);const [err,setErr]=useState('');function s(k,v){setF(x=>({...x,[k]:v}))}async function save(e){e.preventDefault();setBusy(true);setErr('');const payload={organization_id:org,name:f.name.trim(),trade_name:f.trade_name||null,cnpj:f.cnpj||null,city:f.city||null,state:f.state||null,website:f.website||null,general_email:f.general_email||null,phone:f.phone||null,priority:f.priority,stage_id:f.stage_id||null,genres:[],alternate_emails:[],archived:false,created_by:user?.id||null,updated_by:user?.id||null};const {error}=await supabase.from('publishers').insert(payload);if(error){setErr(error.message);setBusy(false)}else onSaved()}return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><h3>Nova editora</h3><p>Cadastre o essencial; os demais dados podem ser completados depois.</p></div><button type="button" onClick={onClose}><X/></button></div>{err&&<div className="notice error">{err}</div>}<div className="form-grid"><label className="span-2">Nome<input className="input" required value={f.name} onChange={e=>s('name',e.target.value)}/></label><label>Nome fantasia<input className="input" value={f.trade_name} onChange={e=>s('trade_name',e.target.value)}/></label><label>CNPJ<input className="input" value={f.cnpj} onChange={e=>s('cnpj',e.target.value)}/></label><label>Cidade<input className="input" value={f.city} onChange={e=>s('city',e.target.value)}/></label><label>UF<input className="input" maxLength={2} value={f.state} onChange={e=>s('state',e.target.value.toUpperCase())}/></label><label>Site<input className="input" value={f.website} onChange={e=>s('website',e.target.value)}/></label><label>E-mail geral<input className="input" type="email" value={f.general_email} onChange={e=>s('general_email',e.target.value)}/></label><label>Telefone<input className="input" value={f.phone} onChange={e=>s('phone',e.target.value)}/></label><label>Prioridade<select value={f.priority} onChange={e=>s('priority',e.target.value)}>{Object.entries(PRIORITY_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Etapa<select value={f.stage_id} onChange={e=>s('stage_id',e.target.value)}><option value="">Sem etapa</option>{stages.map(st=><option key={st.id} value={st.id}>{st.name}</option>)}</select></label></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancelar</button><button className="btn" disabled={busy}>{busy?'Salvando…':'Criar editora'}</button></div></form></div>}
