'use client';
import { useEffect, useMemo, useState } from 'react';
import { BarChart3, CheckCircle2, Flag, Plus, Target, Users, Workflow, X } from 'lucide-react';
import { useCrm } from '@/components/CrmProvider';
import ModalDialog from '@/components/ModalDialog';
import { PtBrDateField } from '@/components/PtBrDateFields';
import { OPPORTUNITY_SERVICE_LABELS, OPPORTUNITY_STAGE_LABELS } from '@/lib/constants';

export default function PerformancePage(){
  const {supabase,membership,team,isManager,user}=useCrm(); const org=membership?.organization_id;
  const [days,setDays]=useState(30); const [data,setData]=useState(null); const [originMetrics,setOriginMetrics]=useState(null); const [opportunityPipeline,setOpportunityPipeline]=useState(null); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState(''); const [showGoal,setShowGoal]=useState(false);
  async function load(){if(!org)return;setLoading(true);const [{data:d,error},{data:origin,error:originError},{data:pipeline,error:pipelineError}]=await Promise.all([supabase.rpc('crm_performance_dashboard',{p_organization_id:org,p_days:days}),supabase.rpc('crm_origin_metrics',{p_organization_id:org}),supabase.rpc('crm_opportunity_pipeline_summary',{p_organization_id:org,p_days:days})]);if(error||originError||pipelineError)setNotice(error?.message||originError?.message||pipelineError?.message);setData(d||null);setOriginMetrics(origin||null);setOpportunityPipeline(pipeline||null);setLoading(false)}
  useEffect(()=>{load()},[org,days]);
  const p=data?.personal||{}; const pipeline=opportunityPipeline||{}; const goals=data?.goals||[];
  const originPersonal=originMetrics?.personal||{};
  const originTeamMap=useMemo(()=>Object.fromEntries((originMetrics?.team||[]).map(item=>[item.user_id,item])),[originMetrics]);
  const myGoal=useMemo(()=>goals.find(g=>g.user_id===user?.id),[goals,user?.id]);
  return <div className="page-wrap">
    <div className="page-head"><div><div className="eyebrow">Gestão comercial</div><h1>Desempenho</h1><p>{isManager?'Acompanhe origem das contas, responsabilidade atual e resultados da equipe.':'Acompanhe contas originadas, responsabilidade atual, interações, tarefas, metas e oportunidades.'}</p></div><div className="chips"><button className={`chip ${days===30?'active':''}`} onClick={()=>setDays(30)}>30 dias</button><button className={`chip ${days===60?'active':''}`} onClick={()=>setDays(60)}>60 dias</button><button className={`chip ${days===90?'active':''}`} onClick={()=>setDays(90)}>90 dias</button></div></div>
    {notice&&<div className="notice-bar"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {loading?<div className="card table-empty">Calculando desempenho…</div>:<>
      <div className="metric-grid"><Metric icon={<Users/>} label="Responsabilidade atual" value={originPersonal.current_responsibility??p.owned_publishers??0} sub="editoras que você conduz agora"/><Metric icon={<Users/>} label="Contas originadas" value={originPersonal.originated_publishers||0} sub="editoras cuja prospecção começou com você"/><Metric icon={<BarChart3/>} label="Interações" value={p.interactions||0} sub={`${p.publishers_contacted||0} editoras diferentes`}/><Metric icon={<CheckCircle2/>} label="Tarefas concluídas" value={p.tasks_done||0} sub={`${p.tasks_overdue||0} atrasadas agora`}/><Metric icon={<Target/>} label="Oportunidades criadas" value={p.opportunities_created||0} sub={`${Number(pipeline.won_period||0).toLocaleString('pt-BR')} ganha${Number(pipeline.won_period||0)===1?'':'s'} no período`}/></div>
      <div className="performance-grid">
        <section className="card panel"><div className="panel-head"><div><h2>Minha meta atual</h2><p>Veja quanto você já avançou em relação aos objetivos do período.</p></div>{isManager&&<button className="btn secondary small" onClick={()=>setShowGoal(true)}><Plus size={14}/> Definir meta</button>}</div>{myGoal?<GoalCard goal={myGoal}/>:<div className="empty-state"><Flag/><strong>Nenhuma meta ativa para você.</strong><p>As métricas continuam sendo acompanhadas normalmente.</p></div>}</section>
        <section className="card panel"><div className="panel-head"><div><h2>Pipeline de oportunidades</h2><p>{isManager?'Acompanhe volume, estágio e serviço das oportunidades da operação sem registrar valores comerciais.':'Acompanhe suas oportunidades por estágio e serviço, sem dados financeiros.'}</p></div><Workflow size={20}/></div><div className="forecast-total"><div><span>Abertas</span><strong>{Number(pipeline.open_total||0).toLocaleString('pt-BR')}</strong></div><div><span>Propostas enviadas</span><strong>{Number(pipeline.proposal_total||0).toLocaleString('pt-BR')}</strong></div><div><span>Em negociação</span><strong>{Number(pipeline.negotiation_total||0).toLocaleString('pt-BR')}</strong></div><div><span>Ganhas no período</span><strong>{Number(pipeline.won_period||0).toLocaleString('pt-BR')}</strong></div></div><div className="forecast-stage-list">{(pipeline.by_stage||[]).map(s=><div className="forecast-stage" key={s.stage}><div><strong>{OPPORTUNITY_STAGE_LABELS[s.stage]||s.stage}</strong><span>{Number(s.count||0).toLocaleString('pt-BR')} oportunidade{Number(s.count||0)===1?'':'s'}</span></div></div>)}</div>{(pipeline.by_service||[]).length>0&&<div className="opportunity-service-summary"><strong>Por serviço</strong>{pipeline.by_service.map(item=><div key={item.service_key}><span>{OPPORTUNITY_SERVICE_LABELS[item.service_key]||'Outro serviço / projeto'}</span><b>{Number(item.open_count||0).toLocaleString('pt-BR')}</b></div>)}</div>}{!(pipeline.by_stage||[]).length&&<p className="muted">Ainda não há oportunidades abertas cadastradas.</p>}</section>
      </div>
      {isManager&&<section className="card panel" style={{marginTop:16}}><div className="panel-head"><div><h2>Painel da equipe</h2><p>Compare origem de contas, responsabilidade atual, interações, tarefas e oportunidades.</p></div><button className="btn secondary small" onClick={()=>setShowGoal(true)}><Flag size={14}/> Metas</button></div><div className="team-performance-table handoff-team-performance"><div className="team-performance-head"><span>Pessoa</span><span>Originadas</span><span>Resp. atual</span><span>Interações</span><span>Tarefas feitas</span><span>Atrasadas</span><span>Oportunidades</span></div>{(data?.team||[]).map(m=>{const origin=originTeamMap[m.user_id]||{};return <div className="team-performance-row" key={m.user_id}><strong>{m.name}</strong><span>{origin.originated_publishers||0}</span><span>{origin.current_responsibility??m.owned_publishers??0}</span><span>{m.interactions}</span><span>{m.tasks_done}</span><span className={m.overdue>0?'danger-text':''}>{m.overdue}</span><span>{m.opportunities}</span></div>})}</div></section>}
      {goals.length>0&&<section className="card panel" style={{marginTop:16}}><div className="panel-head"><div><h2>Metas ativas</h2><p>Acompanhe o progresso das metas que estão em andamento.</p></div></div><div className="goals-grid">{goals.map(g=><GoalCard key={g.id} goal={g}/>)}</div></section>}
    </>}
    {showGoal&&<GoalModal supabase={supabase} org={org} team={team} onClose={()=>setShowGoal(false)} onSaved={()=>{setShowGoal(false);setNotice('Meta salva.');load()}}/>}
  </div>
}
function Metric({icon,label,value,sub}){return <div className="metric-card"><div className="metric-icon">{icon}</div><div><span>{label}</span><strong>{Number(value||0).toLocaleString('pt-BR')}</strong><small>{sub}</small></div></div>}
function pct(actual,target){return target?Math.min(100,Math.round((Number(actual||0)/Number(target))*100)):0}
function GoalCard({goal}){const items=[['Interações',goal.interactions_actual,goal.interactions_target],['Tarefas concluídas',goal.completed_tasks_actual,goal.completed_tasks_target],['Oportunidades criadas',goal.opportunities_actual,goal.opportunities_target]];return <div className="goal-card"><div className="goal-card-head"><div><strong>{goal.name}</strong><span>{goal.period_start} → {goal.period_end}</span></div><Flag size={18}/></div>{items.map(([label,a,t])=><div className="goal-progress" key={label}><div><span>{label}</span><strong>{a||0} / {t||0}</strong></div><div className="bar-track"><div className="bar-fill" style={{width:`${pct(a,t)}%`}}/></div><small>{pct(a,t)}%</small></div>)}</div>}
function GoalModal({supabase,org,team,onClose,onSaved}){const today=new Date();const first=new Date(today.getFullYear(),today.getMonth(),1).toISOString().slice(0,10);const last=new Date(today.getFullYear(),today.getMonth()+1,0).toISOString().slice(0,10);const [f,setF]=useState({user_id:team.find(m=>m.active)?.user_id||'',period_start:first,period_end:last,interactions_target:40,completed_tasks_target:30,opportunities_target:4});const [err,setErr]=useState('');const [busy,setBusy]=useState(false);async function save(e){e.preventDefault();if(busy)return;setBusy(true);setErr('');const payload={organization_id:org,user_id:f.user_id,period_start:f.period_start,period_end:f.period_end,interactions_target:Number(f.interactions_target)||0,completed_tasks_target:Number(f.completed_tasks_target)||0,opportunities_target:Number(f.opportunities_target)||0,updated_at:new Date().toISOString()};const {error}=await supabase.from('sales_goals').upsert(payload,{onConflict:'organization_id,user_id,period_start,period_end'});if(error){setErr(error.message);setBusy(false)}else onSaved()}return <ModalDialog title="Definir meta" description="Escolha a pessoa, o período e os objetivos que serão acompanhados." onClose={onClose} onSubmit={save} busy={busy}>{err&&<div className="notice error" role="alert">{err}</div>}<div className="form-grid"><label className="span-2">Pessoa<select value={f.user_id} onChange={e=>setF(x=>({...x,user_id:e.target.value}))}>{team.filter(m=>m.active).map(m=><option value={m.user_id} key={m.user_id}>{m.full_name||m.email}</option>)}</select></label><label>Início<PtBrDateField value={f.period_start} onChange={value=>setF(x=>({...x,period_start:value}))} ariaLabel="Início"/></label><label>Fim<PtBrDateField value={f.period_end} onChange={value=>setF(x=>({...x,period_end:value}))} ariaLabel="Fim"/></label><label>Meta de interações<input className="input" type="number" min="0" value={f.interactions_target} onChange={e=>setF(x=>({...x,interactions_target:e.target.value}))}/></label><label>Meta de tarefas concluídas<input className="input" type="number" min="0" value={f.completed_tasks_target} onChange={e=>setF(x=>({...x,completed_tasks_target:e.target.value}))}/></label><label className="span-2">Meta de oportunidades<input className="input" type="number" min="0" value={f.opportunities_target} onChange={e=>setF(x=>({...x,opportunities_target:e.target.value}))}/></label></div><div className="modal-actions"><button className="btn secondary" type="button" disabled={busy} onClick={onClose}>Cancelar</button><button className="btn" disabled={busy}>{busy?'Salvando…':'Salvar meta'}</button></div></ModalDialog>}