'use client';
import { useEffect, useMemo, useState } from 'react';
import { BarChart3, CheckCircle2, Flag, Plus, Target, TrendingUp, Users, X } from 'lucide-react';
import { useCrm } from '@/components/CrmProvider';
import { OPPORTUNITY_STAGE_LABELS, currency } from '@/lib/constants';

export default function PerformancePage(){
  const {supabase,membership,team,isManager,user}=useCrm(); const org=membership?.organization_id;
  const [days,setDays]=useState(30); const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState(''); const [showGoal,setShowGoal]=useState(false);
  async function load(){if(!org)return;setLoading(true);const {data:d,error}=await supabase.rpc('crm_performance_dashboard',{p_organization_id:org,p_days:days});if(error)setNotice(error.message);setData(d||null);setLoading(false)}
  useEffect(()=>{load()},[org,days]);
  const p=data?.personal||{}; const forecast=data?.forecast||{}; const goals=data?.goals||[];
  const myGoal=useMemo(()=>goals.find(g=>g.user_id===user?.id),[goals,user?.id]);
  return <div className="page-wrap">
    <div className="page-head"><div><div className="eyebrow">Gestão comercial</div><h1>Desempenho</h1><p>{isManager?'Acompanhe seus resultados e consulte a visão consolidada da equipe.':'Acompanhe sua carteira, interações, tarefas, metas e oportunidades ao longo do período.'}</p></div><div className="chips"><button className={`chip ${days===30?'active':''}`} onClick={()=>setDays(30)}>30 dias</button><button className={`chip ${days===60?'active':''}`} onClick={()=>setDays(60)}>60 dias</button><button className={`chip ${days===90?'active':''}`} onClick={()=>setDays(90)}>90 dias</button></div></div>
    {notice&&<div className="notice-bar"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {loading?<div className="card table-empty">Calculando desempenho…</div>:<>
      <div className="metric-grid"><Metric icon={<Users/>} label="Minha carteira" value={p.owned_publishers||0} sub="editoras sob sua responsabilidade"/><Metric icon={<BarChart3/>} label="Interações" value={p.interactions||0} sub={`${p.publishers_contacted||0} editoras diferentes`}/><Metric icon={<CheckCircle2/>} label="Tarefas concluídas" value={p.tasks_done||0} sub={`${p.tasks_overdue||0} atrasadas agora`}/><Metric icon={<Target/>} label="Oportunidades criadas" value={p.opportunities_created||0} sub={`${currency(p.won_value||0)} ganho no período`}/></div>
      <div className="performance-grid">
        <section className="card panel"><div className="panel-head"><div><h2>Minha meta atual</h2><p>Veja quanto você já avançou em relação aos objetivos do período.</p></div>{isManager&&<button className="btn secondary small" onClick={()=>setShowGoal(true)}><Plus size={14}/> Definir meta</button>}</div>{myGoal?<GoalCard goal={myGoal}/>:<div className="empty-state"><Flag/><strong>Nenhuma meta ativa para você.</strong><p>As métricas continuam sendo acompanhadas normalmente.</p></div>}</section>
        <section className="card panel"><div className="panel-head"><div><h2>{isManager?'Forecast da operação':'Meu forecast'}</h2><p>{isManager?'Veja o valor estimado das oportunidades abertas da equipe considerando a chance de fechamento.':'Veja o valor estimado das suas oportunidades abertas considerando a chance de fechamento.'}</p></div><TrendingUp size={20}/></div><div className="forecast-total"><div><span>Pipeline aberto</span><strong>{currency(forecast.open_value||0)}</strong></div><div><span>Forecast ponderado</span><strong>{currency(forecast.weighted_value||0)}</strong></div></div><div className="forecast-stage-list">{(forecast.by_stage||[]).map(s=><div className="forecast-stage" key={s.stage}><div><strong>{OPPORTUNITY_STAGE_LABELS[s.stage]||s.stage}</strong><span>{s.count} oportunidade{s.count===1?'':'s'}</span></div><div><strong>{currency(s.weighted||0)}</strong><span>de {currency(s.value||0)}</span></div></div>)}</div>{!(forecast.by_stage||[]).length&&<p className="muted">Ainda não há oportunidades abertas com valor estimado.</p>}</section>
      </div>
      {isManager&&<section className="card panel" style={{marginTop:16}}><div className="panel-head"><div><h2>Painel da equipe</h2><p>Compare carteira, interações, tarefas e oportunidades de cada pessoa no período.</p></div><button className="btn secondary small" onClick={()=>setShowGoal(true)}><Flag size={14}/> Metas</button></div><div className="team-performance-table"><div className="team-performance-head"><span>Pessoa</span><span>Carteira</span><span>Interações</span><span>Tarefas feitas</span><span>Atrasadas</span><span>Oportunidades</span></div>{(data?.team||[]).map(m=><div className="team-performance-row" key={m.user_id}><strong>{m.name}</strong><span>{m.owned_publishers}</span><span>{m.interactions}</span><span>{m.tasks_done}</span><span className={m.overdue>0?'danger-text':''}>{m.overdue}</span><span>{m.opportunities}</span></div>)}</div></section>}
      {goals.length>0&&<section className="card panel" style={{marginTop:16}}><div className="panel-head"><div><h2>Metas ativas</h2><p>Acompanhe o progresso das metas que estão em andamento.</p></div></div><div className="goals-grid">{goals.map(g=><GoalCard key={g.id} goal={g}/>)}</div></section>}
    </>}
    {showGoal&&<GoalModal supabase={supabase} org={org} team={team} onClose={()=>setShowGoal(false)} onSaved={()=>{setShowGoal(false);setNotice('Meta salva.');load()}}/>}
  </div>
}
function Metric({icon,label,value,sub}){return <div className="metric-card"><div className="metric-icon">{icon}</div><div><span>{label}</span><strong>{Number(value||0).toLocaleString('pt-BR')}</strong><small>{sub}</small></div></div>}
function pct(actual,target){return target?Math.min(100,Math.round((Number(actual||0)/Number(target))*100)):0}
function GoalCard({goal}){const items=[['Interações',goal.interactions_actual,goal.interactions_target],['Tarefas concluídas',goal.completed_tasks_actual,goal.completed_tasks_target],['Oportunidades criadas',goal.opportunities_actual,goal.opportunities_target]];return <div className="goal-card"><div className="goal-card-head"><div><strong>{goal.name}</strong><span>{goal.period_start} → {goal.period_end}</span></div><Flag size={18}/></div>{items.map(([label,a,t])=><div className="goal-progress" key={label}><div><span>{label}</span><strong>{a||0} / {t||0}</strong></div><div className="bar-track"><div className="bar-fill" style={{width:`${pct(a,t)}%`}}/></div><small>{pct(a,t)}%</small></div>)}</div>}
function GoalModal({supabase,org,team,onClose,onSaved}){const today=new Date();const first=new Date(today.getFullYear(),today.getMonth(),1).toISOString().slice(0,10);const last=new Date(today.getFullYear(),today.getMonth()+1,0).toISOString().slice(0,10);const [f,setF]=useState({user_id:team.find(m=>m.active)?.user_id||'',period_start:first,period_end:last,interactions_target:40,completed_tasks_target:30,opportunities_target:4});const [err,setErr]=useState('');async function save(e){e.preventDefault();const payload={organization_id:org,user_id:f.user_id,period_start:f.period_start,period_end:f.period_end,interactions_target:Number(f.interactions_target)||0,completed_tasks_target:Number(f.completed_tasks_target)||0,opportunities_target:Number(f.opportunities_target)||0,updated_at:new Date().toISOString()};const {error}=await supabase.from('sales_goals').upsert(payload,{onConflict:'organization_id,user_id,period_start,period_end'});if(error)setErr(error.message);else onSaved()}return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><h3>Definir meta</h3><p>Escolha a pessoa, o período e os objetivos que serão acompanhados.</p></div><button type="button" onClick={onClose}><X/></button></div>{err&&<div className="notice error">{err}</div>}<div className="form-grid"><label className="span-2">Pessoa<select value={f.user_id} onChange={e=>setF(x=>({...x,user_id:e.target.value}))}>{team.filter(m=>m.active).map(m=><option value={m.user_id} key={m.user_id}>{m.full_name||m.email}</option>)}</select></label><label>Início<input className="input" type="date" value={f.period_start} onChange={e=>setF(x=>({...x,period_start:e.target.value}))}/></label><label>Fim<input className="input" type="date" value={f.period_end} onChange={e=>setF(x=>({...x,period_end:e.target.value}))}/></label><label>Meta de interações<input className="input" type="number" min="0" value={f.interactions_target} onChange={e=>setF(x=>({...x,interactions_target:e.target.value}))}/></label><label>Meta de tarefas concluídas<input className="input" type="number" min="0" value={f.completed_tasks_target} onChange={e=>setF(x=>({...x,completed_tasks_target:e.target.value}))}/></label><label className="span-2">Meta de oportunidades<input className="input" type="number" min="0" value={f.opportunities_target} onChange={e=>setF(x=>({...x,opportunities_target:e.target.value}))}/></label></div><div className="modal-actions"><button className="btn secondary" type="button" onClick={onClose}>Cancelar</button><button className="btn">Salvar meta</button></div></form></div>}
